use crate::resources::PackFormat;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CommandResult {
    pub success_count: i32,
    pub feedback_key: &'static str,
    pub broadcast_to_admins: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CommandError {
    PermissionDenied,
    InvalidSyntax,
    SaveAlreadyOff,
    SaveAlreadyOn,
    SaveFailed,
    WhitelistAlreadyOn,
    WhitelistAlreadyOff,
    AlreadyWhitelisted,
    NotWhitelisted,
    NoPlayers,
    PublishAlreadyPublished,
    PublishFailed,
    RandomRangeTooSmall,
    RandomRangeTooLarge,
    KickSingleplayer,
    KickOwner,
    BanFailed,
    BanIpInvalid,
    BanIpFailed,
    PardonFailed,
    PardonIpInvalid,
    PardonIpFailed,
    OpFailed,
    DeOpFailed,
    DebugAlreadyRunning,
    DebugNotRunning,
    DebugNoRecursiveTraces,
    DebugNoReturnRun,
    DebugConfigPlayerMissing,
    DebugPathNotMob,
    DebugPathNoPath,
    DebugPathNotComplete,
    DifficultyAlreadySame,
    EffectGiveFailed,
    EffectClearEverythingFailed,
    EffectClearSpecificFailed,
    EnchantNotLivingEntity,
    EnchantNoItem,
    EnchantIncompatible,
    EnchantLevelTooHigh,
    EnchantFailed,
    ExecuteConditionFailed,
    ExperienceSetPointsInvalid,
    FetchProfileNotFound,
    ChaseAlreadyRunning,
    ClearFailedSingle,
    ClearFailedMultiple,
    CloneOverlap,
    CloneTooBig,
    CloneFailed,
    FillTooBig,
    FillFailed,
    FillBiomeTooBig,
    FillBiomeNotLoaded,
    ForceLoadTooBig,
    ForceLoadAlreadyAdded,
    ForceLoadNotForced,
    ForceLoadOutOfWorld,
    LocateStructureInvalid,
    LocateStructureNotFound,
    LocateBiomeNotFound,
    LocatePoiNotFound,
    LootNoHeldItems,
    LootNoEntityLootTable,
    LootNoBlockLootTable,
    PlaceFeatureFailed,
    PlaceJigsawFailed,
    PlaceStructureFailed,
    PlaceTemplateInvalid,
    PlaceTemplateFailed,
    TeleportInvalidPosition,
    TimeNoDefaultClock,
    TimeNoTimeMarkerFound,
    TimeWrongTimeline,
    WaypointInvalid,
    WorldBorderSameCenter,
    WorldBorderSameSize,
    WorldBorderTooSmall,
    WorldBorderTooBig,
    WorldBorderTooFarOut,
    WorldBorderSameWarningTime,
    WorldBorderSameWarningDistance,
    WorldBorderSameDamageBuffer,
    WorldBorderSameDamageAmount,
    DamageInvulnerable,
    DataPackUnknown,
    DataPackAlreadyEnabled,
    DataPackAlreadyDisabled,
    DataPackCannotDisableFeature,
    DataPackFeaturesNotEnabled,
    DataPackInvalidName,
    DataPackInvalidFullName,
    DataPackAlreadyExists,
    HelpFailed,
    TeamMsgNoTeam,
    PlaySoundTooFar,
    ParticleFailed,
    RideNotRiding,
    RideAlreadyRiding,
    RideMountingPlayer,
    RideMountingLoop,
    RideWrongDimension,
    RideMountFailed,
    PerfAlreadyRunning,
    PerfNotRunning,
    JfrStartFailed,
    JfrDumpFailed,
    RecipeGiveFailed,
    RecipeTakeFailed,
    GiveTooManyItems,
    ItemTargetNotContainer,
    ItemSourceNotContainer,
    ItemTargetNoSuchSlot,
    ItemSourceNoSuchSlot,
    ItemTargetNoChanges,
    SwingNoLivingEntity,
    TagAddFailed,
    TagRemoveFailed,
    StopwatchAlreadyExists,
    StopwatchDoesNotExist,
    SpectateSelf,
    SpectateNotSpectator,
    SpectateCannotSpectate,
    SummonFailed,
    SummonFailedPeaceful,
    SummonDuplicateUuid,
    SummonInvalidPosition,
    TeamAlreadyExists,
    TeamNotFound,
    TeamAlreadyEmpty,
    TeamOptionUnchanged,
    SetBlockFailed,
    FunctionNoFunctions,
    FunctionArgumentNotCompound,
    FunctionInstantiationFailure,
    ScheduleSameTick,
    ScheduleCantRemove,
    ScheduleMacro,
    InvalidArmorTrimPattern,
    SpreadPlayersInvalidMaxHeight,
    SpreadPlayersFailedEntities,
    SpreadPlayersFailedTeams,
    ScoreboardObjectiveAlreadyExists,
    ScoreboardObjectiveNotFound,
    ScoreboardScoreNotFound,
    ScoreboardDisplayAlreadyEmpty,
    ScoreboardDisplayAlreadySet,
    ScoreboardTriggerAlreadyEnabled,
    ScoreboardNotTrigger,
    TriggerNotPrimed,
    AdvancementNoAction,
    AdvancementCriterionNotFound,
    AttributeNotLiving,
    AttributeNoSuchAttribute,
    AttributeNoSuchModifier,
    AttributeModifierAlreadyPresent,
    BossBarAlreadyExists,
    BossBarUnknown,
    BossBarPlayersUnchanged,
    BossBarNameUnchanged,
    BossBarColorUnchanged,
    BossBarStyleUnchanged,
    BossBarValueUnchanged,
    BossBarMaxUnchanged,
    BossBarAlreadyHidden,
    BossBarAlreadyVisible,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VersionInfo {
    pub id: &'static str,
    pub name: &'static str,
    pub data_version: i32,
    pub series: &'static str,
    pub protocol_version: i32,
    pub build_time: &'static str,
    pub resource_pack_version: PackFormat,
    pub data_pack_version: PackFormat,
    pub stable: bool,
}
