//! Rename table extracted from the Java source of `AdvancementsFix` (generated data).

/// `AdvancementsFix.RENAMES`.
pub const RENAMES: &[(&str, &str)] = &[
    (
        "minecraft:recipes/brewing/speckled_melon",
        "minecraft:recipes/brewing/glistering_melon_slice",
    ),
    (
        "minecraft:recipes/building_blocks/black_stained_hardened_clay",
        "minecraft:recipes/building_blocks/black_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/blue_stained_hardened_clay",
        "minecraft:recipes/building_blocks/blue_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/brown_stained_hardened_clay",
        "minecraft:recipes/building_blocks/brown_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/cyan_stained_hardened_clay",
        "minecraft:recipes/building_blocks/cyan_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/gray_stained_hardened_clay",
        "minecraft:recipes/building_blocks/gray_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/green_stained_hardened_clay",
        "minecraft:recipes/building_blocks/green_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/light_blue_stained_hardened_clay",
        "minecraft:recipes/building_blocks/light_blue_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/light_gray_stained_hardened_clay",
        "minecraft:recipes/building_blocks/light_gray_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/lime_stained_hardened_clay",
        "minecraft:recipes/building_blocks/lime_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/magenta_stained_hardened_clay",
        "minecraft:recipes/building_blocks/magenta_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/orange_stained_hardened_clay",
        "minecraft:recipes/building_blocks/orange_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/pink_stained_hardened_clay",
        "minecraft:recipes/building_blocks/pink_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/purple_stained_hardened_clay",
        "minecraft:recipes/building_blocks/purple_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/red_stained_hardened_clay",
        "minecraft:recipes/building_blocks/red_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/white_stained_hardened_clay",
        "minecraft:recipes/building_blocks/white_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/yellow_stained_hardened_clay",
        "minecraft:recipes/building_blocks/yellow_terracotta",
    ),
    (
        "minecraft:recipes/building_blocks/acacia_wooden_slab",
        "minecraft:recipes/building_blocks/acacia_slab",
    ),
    (
        "minecraft:recipes/building_blocks/birch_wooden_slab",
        "minecraft:recipes/building_blocks/birch_slab",
    ),
    (
        "minecraft:recipes/building_blocks/dark_oak_wooden_slab",
        "minecraft:recipes/building_blocks/dark_oak_slab",
    ),
    (
        "minecraft:recipes/building_blocks/jungle_wooden_slab",
        "minecraft:recipes/building_blocks/jungle_slab",
    ),
    (
        "minecraft:recipes/building_blocks/oak_wooden_slab",
        "minecraft:recipes/building_blocks/oak_slab",
    ),
    (
        "minecraft:recipes/building_blocks/spruce_wooden_slab",
        "minecraft:recipes/building_blocks/spruce_slab",
    ),
    (
        "minecraft:recipes/building_blocks/brick_block",
        "minecraft:recipes/building_blocks/bricks",
    ),
    (
        "minecraft:recipes/building_blocks/chiseled_stonebrick",
        "minecraft:recipes/building_blocks/chiseled_stone_bricks",
    ),
    (
        "minecraft:recipes/building_blocks/end_bricks",
        "minecraft:recipes/building_blocks/end_stone_bricks",
    ),
    (
        "minecraft:recipes/building_blocks/lit_pumpkin",
        "minecraft:recipes/building_blocks/jack_o_lantern",
    ),
    (
        "minecraft:recipes/building_blocks/magma",
        "minecraft:recipes/building_blocks/magma_block",
    ),
    (
        "minecraft:recipes/building_blocks/melon_block",
        "minecraft:recipes/building_blocks/melon",
    ),
    (
        "minecraft:recipes/building_blocks/mossy_stonebrick",
        "minecraft:recipes/building_blocks/mossy_stone_bricks",
    ),
    (
        "minecraft:recipes/building_blocks/nether_brick",
        "minecraft:recipes/building_blocks/nether_bricks",
    ),
    (
        "minecraft:recipes/building_blocks/pillar_quartz_block",
        "minecraft:recipes/building_blocks/quartz_pillar",
    ),
    (
        "minecraft:recipes/building_blocks/red_nether_brick",
        "minecraft:recipes/building_blocks/red_nether_bricks",
    ),
    (
        "minecraft:recipes/building_blocks/snow",
        "minecraft:recipes/building_blocks/snow_block",
    ),
    (
        "minecraft:recipes/building_blocks/smooth_red_sandstone",
        "minecraft:recipes/building_blocks/cut_red_sandstone",
    ),
    (
        "minecraft:recipes/building_blocks/smooth_sandstone",
        "minecraft:recipes/building_blocks/cut_sandstone",
    ),
    (
        "minecraft:recipes/building_blocks/stonebrick",
        "minecraft:recipes/building_blocks/stone_bricks",
    ),
    (
        "minecraft:recipes/building_blocks/stone_stairs",
        "minecraft:recipes/building_blocks/cobblestone_stairs",
    ),
    (
        "minecraft:recipes/building_blocks/string_to_wool",
        "minecraft:recipes/building_blocks/white_wool_from_string",
    ),
    (
        "minecraft:recipes/decorations/fence",
        "minecraft:recipes/decorations/oak_fence",
    ),
    (
        "minecraft:recipes/decorations/purple_shulker_box",
        "minecraft:recipes/decorations/shulker_box",
    ),
    (
        "minecraft:recipes/decorations/slime",
        "minecraft:recipes/decorations/slime_block",
    ),
    (
        "minecraft:recipes/decorations/snow_layer",
        "minecraft:recipes/decorations/snow",
    ),
    (
        "minecraft:recipes/misc/bone_meal_from_block",
        "minecraft:recipes/misc/bone_meal_from_bone_block",
    ),
    (
        "minecraft:recipes/misc/bone_meal_from_bone",
        "minecraft:recipes/misc/bone_meal",
    ),
    (
        "minecraft:recipes/misc/gold_ingot_from_block",
        "minecraft:recipes/misc/gold_ingot_from_gold_block",
    ),
    (
        "minecraft:recipes/misc/iron_ingot_from_block",
        "minecraft:recipes/misc/iron_ingot_from_iron_block",
    ),
    (
        "minecraft:recipes/redstone/fence_gate",
        "minecraft:recipes/redstone/oak_fence_gate",
    ),
    (
        "minecraft:recipes/redstone/noteblock",
        "minecraft:recipes/redstone/note_block",
    ),
    (
        "minecraft:recipes/redstone/trapdoor",
        "minecraft:recipes/redstone/oak_trapdoor",
    ),
    (
        "minecraft:recipes/redstone/wooden_button",
        "minecraft:recipes/redstone/oak_button",
    ),
    (
        "minecraft:recipes/redstone/wooden_door",
        "minecraft:recipes/redstone/oak_door",
    ),
    (
        "minecraft:recipes/redstone/wooden_pressure_plate",
        "minecraft:recipes/redstone/oak_pressure_plate",
    ),
    (
        "minecraft:recipes/transportation/boat",
        "minecraft:recipes/transportation/oak_boat",
    ),
    (
        "minecraft:recipes/transportation/golden_rail",
        "minecraft:recipes/transportation/powered_rail",
    ),
];
