//! Ports of `net.minecraft.util.datafix.fixes.*`.
//!
//! One module per Java class; each exposes a constructor (usually `fix()`) that
//! returns the [`Fix`](crate::datafix::fix::Fix) the Java constructor builds.
//! Modules ending in a table suffix hold generated lookup data extracted from the
//! Java source of the fix they belong to.

pub mod add_new_choices;
pub mod advancements_fix;
mod advancements_fix_renames;
pub mod advancements_rename_fix;
pub mod bed_item_color_fix;
pub mod block_entity_banner_color_fix;
pub mod block_entity_block_state_fix;
pub mod block_entity_custom_name_to_component_fix;
pub mod block_entity_id_fix;
pub mod block_entity_jukebox_fix;
pub mod block_entity_keep_packed;
pub mod block_entity_shulker_box_color_fix;
pub mod block_name_flattening_fix;
pub mod block_rename_fix;
pub mod block_state_data;
pub mod block_state_structure_template_fix;
pub mod chunk_bed_block_entity_injecter_fix;
pub mod chunk_paletted_storage_fix;
pub mod chunk_structures_template_rename_fix;
mod chunk_structures_template_rename_fix_renames;
pub mod chunk_to_protochunk_fix;
pub mod colorless_shulker_entity_fix;
pub mod entity_armor_stand_silent_fix;
pub mod entity_block_state_fix;
mod entity_block_state_fix_ids;
pub mod entity_cod_salmon_fix;
pub mod entity_custom_name_to_component_fix;
pub mod entity_elder_guardian_split_fix;
pub mod entity_equipment_to_armor_and_hand_fix;
pub mod entity_health_fix;
pub mod entity_horse_saddle_fix;
pub mod entity_horse_split_fix;
pub mod entity_id_fix;
mod entity_id_fix_ids;
pub mod entity_item_frame_direction_fix;
pub mod entity_minecart_identifiers_fix;
pub mod entity_painting_item_frame_direction_fix;
pub mod entity_painting_motive_fix;
pub mod entity_pufferfish_rename_fix;
pub mod entity_redundant_chance_tags_fix;
pub mod entity_rename_fix;
pub mod entity_riding_to_passengers_fix;
pub mod entity_shulker_color_fix;
pub mod entity_skeleton_split_fix;
pub mod entity_string_uuid_fix;
pub mod entity_the_renamening_fix;
mod entity_the_renamening_fix_ids;
pub mod entity_tipped_arrow_fix;
pub mod entity_wolf_color_fix;
pub mod entity_zombie_split_fix;
pub mod entity_zombie_villager_type_fix;
pub mod heightmap_renaming_fix;
pub mod igloo_metadata_removal_fix;
pub mod item_banner_color_fix;
pub mod item_custom_name_to_component_fix;
pub mod item_id_fix;
mod item_id_fix_names;
pub mod item_potion_fix;
mod item_potion_fix_potions;
pub mod item_rename_fix;
pub mod item_shulker_box_color_fix;
pub mod item_spawn_egg_fix;
mod item_spawn_egg_fix_entities;
pub mod item_stack_enchantment_names_fix;
mod item_stack_enchantment_names_fix_map;
pub mod item_stack_map_id_fix;
pub mod item_stack_spawn_egg_fix;
mod item_stack_spawn_egg_fix_map;
pub mod item_stack_tag_fix;
pub mod item_stack_the_flattening_fix;
mod item_stack_the_flattening_fix_tables;
pub mod item_water_potion_fix;
pub mod leaves_fix;
pub mod level_data_generator_options_fix;
mod level_data_generator_options_fix_map;
pub mod level_flat_generator_info_fix;
pub mod mob_spawner_entity_identifiers_fix;
pub mod named_entity_fix;
pub mod named_entity_write_read_fix;
pub mod namespaced_type_rename_fix;
pub mod objective_render_type_fix;
pub mod options_force_vbo_fix;
pub mod options_key_lwjgl3_fix;
mod options_key_lwjgl3_fix_keys;
pub mod options_key_translation_fix;
pub mod options_lower_case_language_fix;
pub mod recipes_fix;
mod recipes_fix_recipes;
pub mod recipes_renamening_fix;
mod recipes_renamening_fix_recipes;
pub mod remove_block_entity_tag_fix;
pub mod renamed_coral_fans_fix;
mod renamed_coral_fans_fix_ids;
pub mod renamed_coral_fix;
pub mod scoreboard_display_name_fix;
pub mod sign_text_strict_json_fix;
pub mod simple_entity_rename_fix;
pub mod simplest_entity_rename_fix;
pub mod stats_counter_fix;
mod stats_counter_fix_tables;
pub mod stats_rename_fix;
pub mod trapped_chest_block_entity_fix;
pub mod villager_set_can_pick_up_loot_fix;
pub mod villager_trade_fix;
pub mod write_and_read_fix;
pub mod written_book_pages_strict_json_fix;
