//! Tests for the DataFixer port.
//!
//! Most cases are *oracle fixtures*: `fixtures/<name>.in` lists inputs and
//! `fixtures/<name>.cases` additionally stores the output that the real
//! Minecraft 26.1.2 `DataFixers.getDataFixer().update(..)` produced for them
//! (generated by running the server jar; the tests themselves never need Java).
//! Each line is `REFERENCE<TAB>from<TAB>to<TAB>input snbt<TAB>expected snbt`.

use crate::datafix::chain::data_fixer;
use crate::datafix::dynamic::equal_unordered;
use crate::datafix::references::by_java_field_name;
use crate::storage::nbt::tag_parser::parse_fully;
use crate::storage::nbt::Tag;

mod fixtures;
mod framework;
mod java_logic;
mod support;

fn parse(snbt: &str) -> Tag {
    parse_fully(snbt).unwrap_or_else(|err| panic!("bad SNBT {snbt}: {err:?}"))
}

/// Runs every case of an oracle fixture file.
fn run_oracle_cases(name: &str, source: &str) {
    let mut count = 0;
    for (index, line) in source.lines().enumerate() {
        if line.trim().is_empty() || line.starts_with('#') {
            continue;
        }
        let parts: Vec<&str> = line.split('\t').collect();
        assert_eq!(parts.len(), 5, "{name}:{}: malformed case", index + 1);
        let reference = by_java_field_name(parts[0])
            .unwrap_or_else(|| panic!("{name}:{}: unknown reference {}", index + 1, parts[0]));
        let from: i32 = parts[1].parse().expect("from version");
        let to: i32 = parts[2].parse().expect("to version");
        let input = parse(parts[3]);
        let expected = parse(parts[4]);
        let actual = data_fixer()
            .update(reference, &input, from, to)
            .unwrap_or_else(|err| panic!("{name}:{}: {err}", index + 1));
        assert!(
            equal_unordered(&actual, &expected),
            "{name}:{} ({} {from}->{to}) mismatch\n input:    {}\n expected: {}\n actual:   {:?}",
            index + 1,
            parts[0],
            parts[3],
            parts[4],
            actual
        );
        count += 1;
    }
    assert!(count > 0, "{name}: no cases");
}
