// GENERATED FILE - DO NOT EDIT. Regenerate with tools/generate_block_states.py
use super::state_data_a::*;
use super::BlockStateEntryData;

pub(super) const ENTRIES: &[BlockStateEntryData] = &[
    BlockStateEntryData {
        registry_id: "minecraft:powder_snow_cauldron",
        block_type: "minecraft:layered_cauldron",
        base_state_id: 9465,
        default_state_id: 9465,
        properties: L53,
    },
    BlockStateEntryData {
        registry_id: "minecraft:end_portal",
        block_type: "minecraft:end_portal",
        base_state_id: 9468,
        default_state_id: 9468,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:end_portal_frame",
        block_type: "minecraft:end_portal_frame",
        base_state_id: 9469,
        default_state_id: 9473,
        properties: L54,
    },
    BlockStateEntryData {
        registry_id: "minecraft:end_stone",
        block_type: "minecraft:block",
        base_state_id: 9477,
        default_state_id: 9477,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dragon_egg",
        block_type: "minecraft:dragon_egg",
        base_state_id: 9478,
        default_state_id: 9478,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:redstone_lamp",
        block_type: "minecraft:redstone_lamp",
        base_state_id: 9479,
        default_state_id: 9480,
        properties: L35,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cocoa",
        block_type: "minecraft:cocoa",
        base_state_id: 9481,
        default_state_id: 9481,
        properties: L55,
    },
    BlockStateEntryData {
        registry_id: "minecraft:sandstone_stairs",
        block_type: "minecraft:stair",
        base_state_id: 9493,
        default_state_id: 9504,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:emerald_ore",
        block_type: "minecraft:drop_experience",
        base_state_id: 9573,
        default_state_id: 9573,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:deepslate_emerald_ore",
        block_type: "minecraft:drop_experience",
        base_state_id: 9574,
        default_state_id: 9574,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:ender_chest",
        block_type: "minecraft:ender_chest",
        base_state_id: 9575,
        default_state_id: 9576,
        properties: L30,
    },
    BlockStateEntryData {
        registry_id: "minecraft:tripwire_hook",
        block_type: "minecraft:trip_wire_hook",
        base_state_id: 9583,
        default_state_id: 9592,
        properties: L56,
    },
    BlockStateEntryData {
        registry_id: "minecraft:tripwire",
        block_type: "minecraft:tripwire",
        base_state_id: 9599,
        default_state_id: 9726,
        properties: L57,
    },
    BlockStateEntryData {
        registry_id: "minecraft:emerald_block",
        block_type: "minecraft:block",
        base_state_id: 9727,
        default_state_id: 9727,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:spruce_stairs",
        block_type: "minecraft:stair",
        base_state_id: 9728,
        default_state_id: 9739,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:birch_stairs",
        block_type: "minecraft:stair",
        base_state_id: 9808,
        default_state_id: 9819,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:jungle_stairs",
        block_type: "minecraft:stair",
        base_state_id: 9888,
        default_state_id: 9899,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:command_block",
        block_type: "minecraft:command",
        base_state_id: 9968,
        default_state_id: 9974,
        properties: L58,
    },
    BlockStateEntryData {
        registry_id: "minecraft:beacon",
        block_type: "minecraft:beacon",
        base_state_id: 9980,
        default_state_id: 9980,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cobblestone_wall",
        block_type: "minecraft:wall",
        base_state_id: 9981,
        default_state_id: 9984,
        properties: L50,
    },
    BlockStateEntryData {
        registry_id: "minecraft:mossy_cobblestone_wall",
        block_type: "minecraft:wall",
        base_state_id: 10305,
        default_state_id: 10308,
        properties: L50,
    },
    BlockStateEntryData {
        registry_id: "minecraft:flower_pot",
        block_type: "minecraft:flower_pot",
        base_state_id: 10629,
        default_state_id: 10629,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_torchflower",
        block_type: "minecraft:flower_pot",
        base_state_id: 10630,
        default_state_id: 10630,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_oak_sapling",
        block_type: "minecraft:flower_pot",
        base_state_id: 10631,
        default_state_id: 10631,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_spruce_sapling",
        block_type: "minecraft:flower_pot",
        base_state_id: 10632,
        default_state_id: 10632,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_birch_sapling",
        block_type: "minecraft:flower_pot",
        base_state_id: 10633,
        default_state_id: 10633,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_jungle_sapling",
        block_type: "minecraft:flower_pot",
        base_state_id: 10634,
        default_state_id: 10634,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_acacia_sapling",
        block_type: "minecraft:flower_pot",
        base_state_id: 10635,
        default_state_id: 10635,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_cherry_sapling",
        block_type: "minecraft:flower_pot",
        base_state_id: 10636,
        default_state_id: 10636,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_dark_oak_sapling",
        block_type: "minecraft:flower_pot",
        base_state_id: 10637,
        default_state_id: 10637,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_pale_oak_sapling",
        block_type: "minecraft:flower_pot",
        base_state_id: 10638,
        default_state_id: 10638,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_mangrove_propagule",
        block_type: "minecraft:flower_pot",
        base_state_id: 10639,
        default_state_id: 10639,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_fern",
        block_type: "minecraft:flower_pot",
        base_state_id: 10640,
        default_state_id: 10640,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_dandelion",
        block_type: "minecraft:flower_pot",
        base_state_id: 10641,
        default_state_id: 10641,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_golden_dandelion",
        block_type: "minecraft:flower_pot",
        base_state_id: 10642,
        default_state_id: 10642,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_poppy",
        block_type: "minecraft:flower_pot",
        base_state_id: 10643,
        default_state_id: 10643,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_blue_orchid",
        block_type: "minecraft:flower_pot",
        base_state_id: 10644,
        default_state_id: 10644,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_allium",
        block_type: "minecraft:flower_pot",
        base_state_id: 10645,
        default_state_id: 10645,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_azure_bluet",
        block_type: "minecraft:flower_pot",
        base_state_id: 10646,
        default_state_id: 10646,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_red_tulip",
        block_type: "minecraft:flower_pot",
        base_state_id: 10647,
        default_state_id: 10647,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_orange_tulip",
        block_type: "minecraft:flower_pot",
        base_state_id: 10648,
        default_state_id: 10648,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_white_tulip",
        block_type: "minecraft:flower_pot",
        base_state_id: 10649,
        default_state_id: 10649,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_pink_tulip",
        block_type: "minecraft:flower_pot",
        base_state_id: 10650,
        default_state_id: 10650,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_oxeye_daisy",
        block_type: "minecraft:flower_pot",
        base_state_id: 10651,
        default_state_id: 10651,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_cornflower",
        block_type: "minecraft:flower_pot",
        base_state_id: 10652,
        default_state_id: 10652,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_lily_of_the_valley",
        block_type: "minecraft:flower_pot",
        base_state_id: 10653,
        default_state_id: 10653,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_wither_rose",
        block_type: "minecraft:flower_pot",
        base_state_id: 10654,
        default_state_id: 10654,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_red_mushroom",
        block_type: "minecraft:flower_pot",
        base_state_id: 10655,
        default_state_id: 10655,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_brown_mushroom",
        block_type: "minecraft:flower_pot",
        base_state_id: 10656,
        default_state_id: 10656,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_dead_bush",
        block_type: "minecraft:flower_pot",
        base_state_id: 10657,
        default_state_id: 10657,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potted_cactus",
        block_type: "minecraft:flower_pot",
        base_state_id: 10658,
        default_state_id: 10658,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:carrots",
        block_type: "minecraft:carrot",
        base_state_id: 10659,
        default_state_id: 10659,
        properties: L25,
    },
    BlockStateEntryData {
        registry_id: "minecraft:potatoes",
        block_type: "minecraft:potato",
        base_state_id: 10667,
        default_state_id: 10667,
        properties: L25,
    },
    BlockStateEntryData {
        registry_id: "minecraft:oak_button",
        block_type: "minecraft:button",
        base_state_id: 10675,
        default_state_id: 10684,
        properties: L33,
    },
    BlockStateEntryData {
        registry_id: "minecraft:spruce_button",
        block_type: "minecraft:button",
        base_state_id: 10699,
        default_state_id: 10708,
        properties: L33,
    },
    BlockStateEntryData {
        registry_id: "minecraft:birch_button",
        block_type: "minecraft:button",
        base_state_id: 10723,
        default_state_id: 10732,
        properties: L33,
    },
    BlockStateEntryData {
        registry_id: "minecraft:jungle_button",
        block_type: "minecraft:button",
        base_state_id: 10747,
        default_state_id: 10756,
        properties: L33,
    },
    BlockStateEntryData {
        registry_id: "minecraft:acacia_button",
        block_type: "minecraft:button",
        base_state_id: 10771,
        default_state_id: 10780,
        properties: L33,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cherry_button",
        block_type: "minecraft:button",
        base_state_id: 10795,
        default_state_id: 10804,
        properties: L33,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dark_oak_button",
        block_type: "minecraft:button",
        base_state_id: 10819,
        default_state_id: 10828,
        properties: L33,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pale_oak_button",
        block_type: "minecraft:button",
        base_state_id: 10843,
        default_state_id: 10852,
        properties: L33,
    },
    BlockStateEntryData {
        registry_id: "minecraft:mangrove_button",
        block_type: "minecraft:button",
        base_state_id: 10867,
        default_state_id: 10876,
        properties: L33,
    },
    BlockStateEntryData {
        registry_id: "minecraft:bamboo_button",
        block_type: "minecraft:button",
        base_state_id: 10891,
        default_state_id: 10900,
        properties: L33,
    },
    BlockStateEntryData {
        registry_id: "minecraft:skeleton_skull",
        block_type: "minecraft:skull",
        base_state_id: 10915,
        default_state_id: 10931,
        properties: L59,
    },
    BlockStateEntryData {
        registry_id: "minecraft:skeleton_wall_skull",
        block_type: "minecraft:wall_skull",
        base_state_id: 10947,
        default_state_id: 10948,
        properties: L60,
    },
    BlockStateEntryData {
        registry_id: "minecraft:wither_skeleton_skull",
        block_type: "minecraft:wither_skull",
        base_state_id: 10955,
        default_state_id: 10971,
        properties: L59,
    },
    BlockStateEntryData {
        registry_id: "minecraft:wither_skeleton_wall_skull",
        block_type: "minecraft:wither_wall_skull",
        base_state_id: 10987,
        default_state_id: 10988,
        properties: L60,
    },
    BlockStateEntryData {
        registry_id: "minecraft:zombie_head",
        block_type: "minecraft:skull",
        base_state_id: 10995,
        default_state_id: 11011,
        properties: L59,
    },
    BlockStateEntryData {
        registry_id: "minecraft:zombie_wall_head",
        block_type: "minecraft:wall_skull",
        base_state_id: 11027,
        default_state_id: 11028,
        properties: L60,
    },
    BlockStateEntryData {
        registry_id: "minecraft:player_head",
        block_type: "minecraft:player_head",
        base_state_id: 11035,
        default_state_id: 11051,
        properties: L59,
    },
    BlockStateEntryData {
        registry_id: "minecraft:player_wall_head",
        block_type: "minecraft:player_wall_head",
        base_state_id: 11067,
        default_state_id: 11068,
        properties: L60,
    },
    BlockStateEntryData {
        registry_id: "minecraft:creeper_head",
        block_type: "minecraft:skull",
        base_state_id: 11075,
        default_state_id: 11091,
        properties: L59,
    },
    BlockStateEntryData {
        registry_id: "minecraft:creeper_wall_head",
        block_type: "minecraft:wall_skull",
        base_state_id: 11107,
        default_state_id: 11108,
        properties: L60,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dragon_head",
        block_type: "minecraft:skull",
        base_state_id: 11115,
        default_state_id: 11131,
        properties: L59,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dragon_wall_head",
        block_type: "minecraft:wall_skull",
        base_state_id: 11147,
        default_state_id: 11148,
        properties: L60,
    },
    BlockStateEntryData {
        registry_id: "minecraft:piglin_head",
        block_type: "minecraft:skull",
        base_state_id: 11155,
        default_state_id: 11171,
        properties: L59,
    },
    BlockStateEntryData {
        registry_id: "minecraft:piglin_wall_head",
        block_type: "minecraft:piglinwallskull",
        base_state_id: 11187,
        default_state_id: 11188,
        properties: L60,
    },
    BlockStateEntryData {
        registry_id: "minecraft:anvil",
        block_type: "minecraft:anvil",
        base_state_id: 11195,
        default_state_id: 11195,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:chipped_anvil",
        block_type: "minecraft:anvil",
        base_state_id: 11199,
        default_state_id: 11199,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:damaged_anvil",
        block_type: "minecraft:anvil",
        base_state_id: 11203,
        default_state_id: 11203,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:trapped_chest",
        block_type: "minecraft:trapped_chest",
        base_state_id: 11207,
        default_state_id: 11208,
        properties: L23,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_weighted_pressure_plate",
        block_type: "minecraft:weighted_pressure_plate",
        base_state_id: 11231,
        default_state_id: 11231,
        properties: L61,
    },
    BlockStateEntryData {
        registry_id: "minecraft:heavy_weighted_pressure_plate",
        block_type: "minecraft:weighted_pressure_plate",
        base_state_id: 11247,
        default_state_id: 11247,
        properties: L61,
    },
    BlockStateEntryData {
        registry_id: "minecraft:comparator",
        block_type: "minecraft:comparator",
        base_state_id: 11263,
        default_state_id: 11264,
        properties: L62,
    },
    BlockStateEntryData {
        registry_id: "minecraft:daylight_detector",
        block_type: "minecraft:daylight_detector",
        base_state_id: 11279,
        default_state_id: 11295,
        properties: L63,
    },
    BlockStateEntryData {
        registry_id: "minecraft:redstone_block",
        block_type: "minecraft:powered",
        base_state_id: 11311,
        default_state_id: 11311,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:nether_quartz_ore",
        block_type: "minecraft:drop_experience",
        base_state_id: 11312,
        default_state_id: 11312,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:hopper",
        block_type: "minecraft:hopper",
        base_state_id: 11313,
        default_state_id: 11313,
        properties: L64,
    },
    BlockStateEntryData {
        registry_id: "minecraft:quartz_block",
        block_type: "minecraft:block",
        base_state_id: 11323,
        default_state_id: 11323,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:chiseled_quartz_block",
        block_type: "minecraft:block",
        base_state_id: 11324,
        default_state_id: 11324,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:quartz_pillar",
        block_type: "minecraft:rotated_pillar",
        base_state_id: 11325,
        default_state_id: 11326,
        properties: L1,
    },
    BlockStateEntryData {
        registry_id: "minecraft:quartz_stairs",
        block_type: "minecraft:stair",
        base_state_id: 11328,
        default_state_id: 11339,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:activator_rail",
        block_type: "minecraft:powered_rail",
        base_state_id: 11408,
        default_state_id: 11421,
        properties: L11,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dropper",
        block_type: "minecraft:dropper",
        base_state_id: 11432,
        default_state_id: 11433,
        properties: L8,
    },
    BlockStateEntryData {
        registry_id: "minecraft:white_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11444,
        default_state_id: 11444,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:orange_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11445,
        default_state_id: 11445,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:magenta_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11446,
        default_state_id: 11446,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_blue_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11447,
        default_state_id: 11447,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:yellow_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11448,
        default_state_id: 11448,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:lime_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11449,
        default_state_id: 11449,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pink_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11450,
        default_state_id: 11450,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:gray_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11451,
        default_state_id: 11451,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_gray_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11452,
        default_state_id: 11452,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cyan_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11453,
        default_state_id: 11453,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purple_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11454,
        default_state_id: 11454,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:blue_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11455,
        default_state_id: 11455,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brown_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11456,
        default_state_id: 11456,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:green_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11457,
        default_state_id: 11457,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11458,
        default_state_id: 11458,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:black_terracotta",
        block_type: "minecraft:block",
        base_state_id: 11459,
        default_state_id: 11459,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:white_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11460,
        default_state_id: 11491,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:orange_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11492,
        default_state_id: 11523,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:magenta_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11524,
        default_state_id: 11555,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_blue_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11556,
        default_state_id: 11587,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:yellow_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11588,
        default_state_id: 11619,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:lime_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11620,
        default_state_id: 11651,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pink_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11652,
        default_state_id: 11683,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:gray_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11684,
        default_state_id: 11715,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_gray_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11716,
        default_state_id: 11747,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cyan_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11748,
        default_state_id: 11779,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purple_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11780,
        default_state_id: 11811,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:blue_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11812,
        default_state_id: 11843,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brown_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11844,
        default_state_id: 11875,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:green_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11876,
        default_state_id: 11907,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11908,
        default_state_id: 11939,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:black_stained_glass_pane",
        block_type: "minecraft:stained_glass_pane",
        base_state_id: 11940,
        default_state_id: 11971,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:acacia_stairs",
        block_type: "minecraft:stair",
        base_state_id: 11972,
        default_state_id: 11983,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cherry_stairs",
        block_type: "minecraft:stair",
        base_state_id: 12052,
        default_state_id: 12063,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dark_oak_stairs",
        block_type: "minecraft:stair",
        base_state_id: 12132,
        default_state_id: 12143,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pale_oak_stairs",
        block_type: "minecraft:stair",
        base_state_id: 12212,
        default_state_id: 12223,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:mangrove_stairs",
        block_type: "minecraft:stair",
        base_state_id: 12292,
        default_state_id: 12303,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:bamboo_stairs",
        block_type: "minecraft:stair",
        base_state_id: 12372,
        default_state_id: 12383,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:bamboo_mosaic_stairs",
        block_type: "minecraft:stair",
        base_state_id: 12452,
        default_state_id: 12463,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:slime_block",
        block_type: "minecraft:slime",
        base_state_id: 12532,
        default_state_id: 12532,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:barrier",
        block_type: "minecraft:barrier",
        base_state_id: 12533,
        default_state_id: 12534,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light",
        block_type: "minecraft:light",
        base_state_id: 12535,
        default_state_id: 12566,
        properties: L65,
    },
    BlockStateEntryData {
        registry_id: "minecraft:iron_trapdoor",
        block_type: "minecraft:trapdoor",
        base_state_id: 12567,
        default_state_id: 12582,
        properties: L43,
    },
    BlockStateEntryData {
        registry_id: "minecraft:prismarine",
        block_type: "minecraft:block",
        base_state_id: 12631,
        default_state_id: 12631,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:prismarine_bricks",
        block_type: "minecraft:block",
        base_state_id: 12632,
        default_state_id: 12632,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dark_prismarine",
        block_type: "minecraft:block",
        base_state_id: 12633,
        default_state_id: 12633,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:prismarine_stairs",
        block_type: "minecraft:stair",
        base_state_id: 12634,
        default_state_id: 12645,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:prismarine_brick_stairs",
        block_type: "minecraft:stair",
        base_state_id: 12714,
        default_state_id: 12725,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dark_prismarine_stairs",
        block_type: "minecraft:stair",
        base_state_id: 12794,
        default_state_id: 12805,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:prismarine_slab",
        block_type: "minecraft:slab",
        base_state_id: 12874,
        default_state_id: 12877,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:prismarine_brick_slab",
        block_type: "minecraft:slab",
        base_state_id: 12880,
        default_state_id: 12883,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dark_prismarine_slab",
        block_type: "minecraft:slab",
        base_state_id: 12886,
        default_state_id: 12889,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:sea_lantern",
        block_type: "minecraft:block",
        base_state_id: 12892,
        default_state_id: 12892,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:hay_block",
        block_type: "minecraft:hay",
        base_state_id: 12893,
        default_state_id: 12894,
        properties: L1,
    },
    BlockStateEntryData {
        registry_id: "minecraft:white_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12896,
        default_state_id: 12896,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:orange_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12897,
        default_state_id: 12897,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:magenta_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12898,
        default_state_id: 12898,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_blue_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12899,
        default_state_id: 12899,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:yellow_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12900,
        default_state_id: 12900,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:lime_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12901,
        default_state_id: 12901,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pink_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12902,
        default_state_id: 12902,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:gray_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12903,
        default_state_id: 12903,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_gray_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12904,
        default_state_id: 12904,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cyan_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12905,
        default_state_id: 12905,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purple_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12906,
        default_state_id: 12906,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:blue_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12907,
        default_state_id: 12907,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brown_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12908,
        default_state_id: 12908,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:green_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12909,
        default_state_id: 12909,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12910,
        default_state_id: 12910,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:black_carpet",
        block_type: "minecraft:wool_carpet",
        base_state_id: 12911,
        default_state_id: 12911,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:terracotta",
        block_type: "minecraft:block",
        base_state_id: 12912,
        default_state_id: 12912,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:coal_block",
        block_type: "minecraft:block",
        base_state_id: 12913,
        default_state_id: 12913,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:packed_ice",
        block_type: "minecraft:block",
        base_state_id: 12914,
        default_state_id: 12914,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:sunflower",
        block_type: "minecraft:tall_flower",
        base_state_id: 12915,
        default_state_id: 12916,
        properties: L13,
    },
    BlockStateEntryData {
        registry_id: "minecraft:lilac",
        block_type: "minecraft:tall_flower",
        base_state_id: 12917,
        default_state_id: 12918,
        properties: L13,
    },
    BlockStateEntryData {
        registry_id: "minecraft:rose_bush",
        block_type: "minecraft:tall_flower",
        base_state_id: 12919,
        default_state_id: 12920,
        properties: L13,
    },
    BlockStateEntryData {
        registry_id: "minecraft:peony",
        block_type: "minecraft:tall_flower",
        base_state_id: 12921,
        default_state_id: 12922,
        properties: L13,
    },
    BlockStateEntryData {
        registry_id: "minecraft:tall_grass",
        block_type: "minecraft:double_plant",
        base_state_id: 12923,
        default_state_id: 12924,
        properties: L13,
    },
    BlockStateEntryData {
        registry_id: "minecraft:large_fern",
        block_type: "minecraft:double_plant",
        base_state_id: 12925,
        default_state_id: 12926,
        properties: L13,
    },
    BlockStateEntryData {
        registry_id: "minecraft:white_banner",
        block_type: "minecraft:banner",
        base_state_id: 12927,
        default_state_id: 12935,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:orange_banner",
        block_type: "minecraft:banner",
        base_state_id: 12943,
        default_state_id: 12951,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:magenta_banner",
        block_type: "minecraft:banner",
        base_state_id: 12959,
        default_state_id: 12967,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_blue_banner",
        block_type: "minecraft:banner",
        base_state_id: 12975,
        default_state_id: 12983,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:yellow_banner",
        block_type: "minecraft:banner",
        base_state_id: 12991,
        default_state_id: 12999,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:lime_banner",
        block_type: "minecraft:banner",
        base_state_id: 13007,
        default_state_id: 13015,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pink_banner",
        block_type: "minecraft:banner",
        base_state_id: 13023,
        default_state_id: 13031,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:gray_banner",
        block_type: "minecraft:banner",
        base_state_id: 13039,
        default_state_id: 13047,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_gray_banner",
        block_type: "minecraft:banner",
        base_state_id: 13055,
        default_state_id: 13063,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cyan_banner",
        block_type: "minecraft:banner",
        base_state_id: 13071,
        default_state_id: 13079,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purple_banner",
        block_type: "minecraft:banner",
        base_state_id: 13087,
        default_state_id: 13095,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:blue_banner",
        block_type: "minecraft:banner",
        base_state_id: 13103,
        default_state_id: 13111,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brown_banner",
        block_type: "minecraft:banner",
        base_state_id: 13119,
        default_state_id: 13127,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:green_banner",
        block_type: "minecraft:banner",
        base_state_id: 13135,
        default_state_id: 13143,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_banner",
        block_type: "minecraft:banner",
        base_state_id: 13151,
        default_state_id: 13159,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:black_banner",
        block_type: "minecraft:banner",
        base_state_id: 13167,
        default_state_id: 13175,
        properties: L66,
    },
    BlockStateEntryData {
        registry_id: "minecraft:white_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13183,
        default_state_id: 13183,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:orange_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13187,
        default_state_id: 13187,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:magenta_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13191,
        default_state_id: 13191,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_blue_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13195,
        default_state_id: 13195,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:yellow_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13199,
        default_state_id: 13199,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:lime_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13203,
        default_state_id: 13203,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pink_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13207,
        default_state_id: 13207,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:gray_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13211,
        default_state_id: 13211,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_gray_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13215,
        default_state_id: 13215,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cyan_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13219,
        default_state_id: 13219,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purple_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13223,
        default_state_id: 13223,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:blue_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13227,
        default_state_id: 13227,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brown_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13231,
        default_state_id: 13231,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:green_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13235,
        default_state_id: 13235,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13239,
        default_state_id: 13239,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:black_wall_banner",
        block_type: "minecraft:wall_banner",
        base_state_id: 13243,
        default_state_id: 13243,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_sandstone",
        block_type: "minecraft:block",
        base_state_id: 13247,
        default_state_id: 13247,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:chiseled_red_sandstone",
        block_type: "minecraft:block",
        base_state_id: 13248,
        default_state_id: 13248,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cut_red_sandstone",
        block_type: "minecraft:block",
        base_state_id: 13249,
        default_state_id: 13249,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_sandstone_stairs",
        block_type: "minecraft:stair",
        base_state_id: 13250,
        default_state_id: 13261,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:oak_slab",
        block_type: "minecraft:slab",
        base_state_id: 13330,
        default_state_id: 13333,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:spruce_slab",
        block_type: "minecraft:slab",
        base_state_id: 13336,
        default_state_id: 13339,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:birch_slab",
        block_type: "minecraft:slab",
        base_state_id: 13342,
        default_state_id: 13345,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:jungle_slab",
        block_type: "minecraft:slab",
        base_state_id: 13348,
        default_state_id: 13351,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:acacia_slab",
        block_type: "minecraft:slab",
        base_state_id: 13354,
        default_state_id: 13357,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cherry_slab",
        block_type: "minecraft:slab",
        base_state_id: 13360,
        default_state_id: 13363,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dark_oak_slab",
        block_type: "minecraft:slab",
        base_state_id: 13366,
        default_state_id: 13369,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pale_oak_slab",
        block_type: "minecraft:slab",
        base_state_id: 13372,
        default_state_id: 13375,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:mangrove_slab",
        block_type: "minecraft:slab",
        base_state_id: 13378,
        default_state_id: 13381,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:bamboo_slab",
        block_type: "minecraft:slab",
        base_state_id: 13384,
        default_state_id: 13387,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:bamboo_mosaic_slab",
        block_type: "minecraft:slab",
        base_state_id: 13390,
        default_state_id: 13393,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:stone_slab",
        block_type: "minecraft:slab",
        base_state_id: 13396,
        default_state_id: 13399,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:smooth_stone_slab",
        block_type: "minecraft:slab",
        base_state_id: 13402,
        default_state_id: 13405,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:sandstone_slab",
        block_type: "minecraft:slab",
        base_state_id: 13408,
        default_state_id: 13411,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cut_sandstone_slab",
        block_type: "minecraft:slab",
        base_state_id: 13414,
        default_state_id: 13417,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:petrified_oak_slab",
        block_type: "minecraft:slab",
        base_state_id: 13420,
        default_state_id: 13423,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cobblestone_slab",
        block_type: "minecraft:slab",
        base_state_id: 13426,
        default_state_id: 13429,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brick_slab",
        block_type: "minecraft:slab",
        base_state_id: 13432,
        default_state_id: 13435,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:stone_brick_slab",
        block_type: "minecraft:slab",
        base_state_id: 13438,
        default_state_id: 13441,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:mud_brick_slab",
        block_type: "minecraft:slab",
        base_state_id: 13444,
        default_state_id: 13447,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:nether_brick_slab",
        block_type: "minecraft:slab",
        base_state_id: 13450,
        default_state_id: 13453,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:quartz_slab",
        block_type: "minecraft:slab",
        base_state_id: 13456,
        default_state_id: 13459,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_sandstone_slab",
        block_type: "minecraft:slab",
        base_state_id: 13462,
        default_state_id: 13465,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cut_red_sandstone_slab",
        block_type: "minecraft:slab",
        base_state_id: 13468,
        default_state_id: 13471,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purpur_slab",
        block_type: "minecraft:slab",
        base_state_id: 13474,
        default_state_id: 13477,
        properties: L49,
    },
    BlockStateEntryData {
        registry_id: "minecraft:smooth_stone",
        block_type: "minecraft:block",
        base_state_id: 13480,
        default_state_id: 13480,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:smooth_sandstone",
        block_type: "minecraft:block",
        base_state_id: 13481,
        default_state_id: 13481,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:smooth_quartz",
        block_type: "minecraft:block",
        base_state_id: 13482,
        default_state_id: 13482,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:smooth_red_sandstone",
        block_type: "minecraft:block",
        base_state_id: 13483,
        default_state_id: 13483,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:spruce_fence_gate",
        block_type: "minecraft:fence_gate",
        base_state_id: 13484,
        default_state_id: 13491,
        properties: L48,
    },
    BlockStateEntryData {
        registry_id: "minecraft:birch_fence_gate",
        block_type: "minecraft:fence_gate",
        base_state_id: 13516,
        default_state_id: 13523,
        properties: L48,
    },
    BlockStateEntryData {
        registry_id: "minecraft:jungle_fence_gate",
        block_type: "minecraft:fence_gate",
        base_state_id: 13548,
        default_state_id: 13555,
        properties: L48,
    },
    BlockStateEntryData {
        registry_id: "minecraft:acacia_fence_gate",
        block_type: "minecraft:fence_gate",
        base_state_id: 13580,
        default_state_id: 13587,
        properties: L48,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cherry_fence_gate",
        block_type: "minecraft:fence_gate",
        base_state_id: 13612,
        default_state_id: 13619,
        properties: L48,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dark_oak_fence_gate",
        block_type: "minecraft:fence_gate",
        base_state_id: 13644,
        default_state_id: 13651,
        properties: L48,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pale_oak_fence_gate",
        block_type: "minecraft:fence_gate",
        base_state_id: 13676,
        default_state_id: 13683,
        properties: L48,
    },
    BlockStateEntryData {
        registry_id: "minecraft:mangrove_fence_gate",
        block_type: "minecraft:fence_gate",
        base_state_id: 13708,
        default_state_id: 13715,
        properties: L48,
    },
    BlockStateEntryData {
        registry_id: "minecraft:bamboo_fence_gate",
        block_type: "minecraft:fence_gate",
        base_state_id: 13740,
        default_state_id: 13747,
        properties: L48,
    },
    BlockStateEntryData {
        registry_id: "minecraft:spruce_fence",
        block_type: "minecraft:fence",
        base_state_id: 13772,
        default_state_id: 13803,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:birch_fence",
        block_type: "minecraft:fence",
        base_state_id: 13804,
        default_state_id: 13835,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:jungle_fence",
        block_type: "minecraft:fence",
        base_state_id: 13836,
        default_state_id: 13867,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:acacia_fence",
        block_type: "minecraft:fence",
        base_state_id: 13868,
        default_state_id: 13899,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cherry_fence",
        block_type: "minecraft:fence",
        base_state_id: 13900,
        default_state_id: 13931,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dark_oak_fence",
        block_type: "minecraft:fence",
        base_state_id: 13932,
        default_state_id: 13963,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pale_oak_fence",
        block_type: "minecraft:fence",
        base_state_id: 13964,
        default_state_id: 13995,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:mangrove_fence",
        block_type: "minecraft:fence",
        base_state_id: 13996,
        default_state_id: 14027,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:bamboo_fence",
        block_type: "minecraft:fence",
        base_state_id: 14028,
        default_state_id: 14059,
        properties: L39,
    },
    BlockStateEntryData {
        registry_id: "minecraft:spruce_door",
        block_type: "minecraft:door",
        base_state_id: 14060,
        default_state_id: 14071,
        properties: L29,
    },
    BlockStateEntryData {
        registry_id: "minecraft:birch_door",
        block_type: "minecraft:door",
        base_state_id: 14124,
        default_state_id: 14135,
        properties: L29,
    },
    BlockStateEntryData {
        registry_id: "minecraft:jungle_door",
        block_type: "minecraft:door",
        base_state_id: 14188,
        default_state_id: 14199,
        properties: L29,
    },
    BlockStateEntryData {
        registry_id: "minecraft:acacia_door",
        block_type: "minecraft:door",
        base_state_id: 14252,
        default_state_id: 14263,
        properties: L29,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cherry_door",
        block_type: "minecraft:door",
        base_state_id: 14316,
        default_state_id: 14327,
        properties: L29,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dark_oak_door",
        block_type: "minecraft:door",
        base_state_id: 14380,
        default_state_id: 14391,
        properties: L29,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pale_oak_door",
        block_type: "minecraft:door",
        base_state_id: 14444,
        default_state_id: 14455,
        properties: L29,
    },
    BlockStateEntryData {
        registry_id: "minecraft:mangrove_door",
        block_type: "minecraft:door",
        base_state_id: 14508,
        default_state_id: 14519,
        properties: L29,
    },
    BlockStateEntryData {
        registry_id: "minecraft:bamboo_door",
        block_type: "minecraft:door",
        base_state_id: 14572,
        default_state_id: 14583,
        properties: L29,
    },
    BlockStateEntryData {
        registry_id: "minecraft:end_rod",
        block_type: "minecraft:end_rod",
        base_state_id: 14636,
        default_state_id: 14640,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:chorus_plant",
        block_type: "minecraft:chorus_plant",
        base_state_id: 14642,
        default_state_id: 14705,
        properties: L44,
    },
    BlockStateEntryData {
        registry_id: "minecraft:chorus_flower",
        block_type: "minecraft:chorus_flower",
        base_state_id: 14706,
        default_state_id: 14706,
        properties: L68,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purpur_block",
        block_type: "minecraft:block",
        base_state_id: 14712,
        default_state_id: 14712,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purpur_pillar",
        block_type: "minecraft:rotated_pillar",
        base_state_id: 14713,
        default_state_id: 14714,
        properties: L1,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purpur_stairs",
        block_type: "minecraft:stair",
        base_state_id: 14716,
        default_state_id: 14727,
        properties: L22,
    },
    BlockStateEntryData {
        registry_id: "minecraft:end_stone_bricks",
        block_type: "minecraft:block",
        base_state_id: 14796,
        default_state_id: 14796,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:torchflower_crop",
        block_type: "minecraft:torchflower_crop",
        base_state_id: 14797,
        default_state_id: 14797,
        properties: L69,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pitcher_crop",
        block_type: "minecraft:pitcher_crop",
        base_state_id: 14799,
        default_state_id: 14800,
        properties: L70,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pitcher_plant",
        block_type: "minecraft:double_plant",
        base_state_id: 14809,
        default_state_id: 14810,
        properties: L13,
    },
    BlockStateEntryData {
        registry_id: "minecraft:beetroots",
        block_type: "minecraft:beetroot",
        base_state_id: 14811,
        default_state_id: 14811,
        properties: L51,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dirt_path",
        block_type: "minecraft:dirt_path",
        base_state_id: 14815,
        default_state_id: 14815,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:end_gateway",
        block_type: "minecraft:end_gateway",
        base_state_id: 14816,
        default_state_id: 14816,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:repeating_command_block",
        block_type: "minecraft:command",
        base_state_id: 14817,
        default_state_id: 14823,
        properties: L58,
    },
    BlockStateEntryData {
        registry_id: "minecraft:chain_command_block",
        block_type: "minecraft:command",
        base_state_id: 14829,
        default_state_id: 14835,
        properties: L58,
    },
    BlockStateEntryData {
        registry_id: "minecraft:frosted_ice",
        block_type: "minecraft:frosted_ice",
        base_state_id: 14841,
        default_state_id: 14841,
        properties: L51,
    },
    BlockStateEntryData {
        registry_id: "minecraft:magma_block",
        block_type: "minecraft:magma",
        base_state_id: 14845,
        default_state_id: 14845,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:nether_wart_block",
        block_type: "minecraft:block",
        base_state_id: 14846,
        default_state_id: 14846,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_nether_bricks",
        block_type: "minecraft:block",
        base_state_id: 14847,
        default_state_id: 14847,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:bone_block",
        block_type: "minecraft:rotated_pillar",
        base_state_id: 14848,
        default_state_id: 14849,
        properties: L1,
    },
    BlockStateEntryData {
        registry_id: "minecraft:structure_void",
        block_type: "minecraft:structure_void",
        base_state_id: 14851,
        default_state_id: 14851,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:observer",
        block_type: "minecraft:observer",
        base_state_id: 14852,
        default_state_id: 14857,
        properties: L71,
    },
    BlockStateEntryData {
        registry_id: "minecraft:shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14864,
        default_state_id: 14868,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:white_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14870,
        default_state_id: 14874,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:orange_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14876,
        default_state_id: 14880,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:magenta_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14882,
        default_state_id: 14886,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_blue_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14888,
        default_state_id: 14892,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:yellow_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14894,
        default_state_id: 14898,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:lime_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14900,
        default_state_id: 14904,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pink_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14906,
        default_state_id: 14910,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:gray_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14912,
        default_state_id: 14916,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_gray_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14918,
        default_state_id: 14922,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cyan_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14924,
        default_state_id: 14928,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purple_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14930,
        default_state_id: 14934,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:blue_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14936,
        default_state_id: 14940,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brown_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14942,
        default_state_id: 14946,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:green_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14948,
        default_state_id: 14952,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14954,
        default_state_id: 14958,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:black_shulker_box",
        block_type: "minecraft:shulker_box",
        base_state_id: 14960,
        default_state_id: 14964,
        properties: L67,
    },
    BlockStateEntryData {
        registry_id: "minecraft:white_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 14966,
        default_state_id: 14966,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:orange_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 14970,
        default_state_id: 14970,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:magenta_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 14974,
        default_state_id: 14974,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_blue_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 14978,
        default_state_id: 14978,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:yellow_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 14982,
        default_state_id: 14982,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:lime_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 14986,
        default_state_id: 14986,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pink_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 14990,
        default_state_id: 14990,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:gray_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 14994,
        default_state_id: 14994,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_gray_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 14998,
        default_state_id: 14998,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cyan_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 15002,
        default_state_id: 15002,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purple_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 15006,
        default_state_id: 15006,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:blue_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 15010,
        default_state_id: 15010,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brown_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 15014,
        default_state_id: 15014,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:green_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 15018,
        default_state_id: 15018,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 15022,
        default_state_id: 15022,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:black_glazed_terracotta",
        block_type: "minecraft:glazed_terracotta",
        base_state_id: 15026,
        default_state_id: 15026,
        properties: L19,
    },
    BlockStateEntryData {
        registry_id: "minecraft:white_concrete",
        block_type: "minecraft:block",
        base_state_id: 15030,
        default_state_id: 15030,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:orange_concrete",
        block_type: "minecraft:block",
        base_state_id: 15031,
        default_state_id: 15031,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:magenta_concrete",
        block_type: "minecraft:block",
        base_state_id: 15032,
        default_state_id: 15032,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_blue_concrete",
        block_type: "minecraft:block",
        base_state_id: 15033,
        default_state_id: 15033,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:yellow_concrete",
        block_type: "minecraft:block",
        base_state_id: 15034,
        default_state_id: 15034,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:lime_concrete",
        block_type: "minecraft:block",
        base_state_id: 15035,
        default_state_id: 15035,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pink_concrete",
        block_type: "minecraft:block",
        base_state_id: 15036,
        default_state_id: 15036,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:gray_concrete",
        block_type: "minecraft:block",
        base_state_id: 15037,
        default_state_id: 15037,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_gray_concrete",
        block_type: "minecraft:block",
        base_state_id: 15038,
        default_state_id: 15038,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cyan_concrete",
        block_type: "minecraft:block",
        base_state_id: 15039,
        default_state_id: 15039,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purple_concrete",
        block_type: "minecraft:block",
        base_state_id: 15040,
        default_state_id: 15040,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:blue_concrete",
        block_type: "minecraft:block",
        base_state_id: 15041,
        default_state_id: 15041,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brown_concrete",
        block_type: "minecraft:block",
        base_state_id: 15042,
        default_state_id: 15042,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:green_concrete",
        block_type: "minecraft:block",
        base_state_id: 15043,
        default_state_id: 15043,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_concrete",
        block_type: "minecraft:block",
        base_state_id: 15044,
        default_state_id: 15044,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:black_concrete",
        block_type: "minecraft:block",
        base_state_id: 15045,
        default_state_id: 15045,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:white_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15046,
        default_state_id: 15046,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:orange_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15047,
        default_state_id: 15047,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:magenta_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15048,
        default_state_id: 15048,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_blue_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15049,
        default_state_id: 15049,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:yellow_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15050,
        default_state_id: 15050,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:lime_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15051,
        default_state_id: 15051,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:pink_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15052,
        default_state_id: 15052,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:gray_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15053,
        default_state_id: 15053,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:light_gray_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15054,
        default_state_id: 15054,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:cyan_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15055,
        default_state_id: 15055,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:purple_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15056,
        default_state_id: 15056,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:blue_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15057,
        default_state_id: 15057,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brown_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15058,
        default_state_id: 15058,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:green_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15059,
        default_state_id: 15059,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:red_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15060,
        default_state_id: 15060,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:black_concrete_powder",
        block_type: "minecraft:concrete_powder",
        base_state_id: 15061,
        default_state_id: 15061,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:kelp",
        block_type: "minecraft:kelp",
        base_state_id: 15062,
        default_state_id: 15062,
        properties: L72,
    },
    BlockStateEntryData {
        registry_id: "minecraft:kelp_plant",
        block_type: "minecraft:kelp_plant",
        base_state_id: 15088,
        default_state_id: 15088,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dried_kelp_block",
        block_type: "minecraft:block",
        base_state_id: 15089,
        default_state_id: 15089,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:turtle_egg",
        block_type: "minecraft:turtle_egg",
        base_state_id: 15090,
        default_state_id: 15090,
        properties: L73,
    },
    BlockStateEntryData {
        registry_id: "minecraft:sniffer_egg",
        block_type: "minecraft:sniffer_egg",
        base_state_id: 15102,
        default_state_id: 15102,
        properties: L74,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dried_ghast",
        block_type: "minecraft:dried_ghast",
        base_state_id: 15105,
        default_state_id: 15106,
        properties: L75,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_tube_coral_block",
        block_type: "minecraft:block",
        base_state_id: 15137,
        default_state_id: 15137,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_brain_coral_block",
        block_type: "minecraft:block",
        base_state_id: 15138,
        default_state_id: 15138,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_bubble_coral_block",
        block_type: "minecraft:block",
        base_state_id: 15139,
        default_state_id: 15139,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_fire_coral_block",
        block_type: "minecraft:block",
        base_state_id: 15140,
        default_state_id: 15140,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_horn_coral_block",
        block_type: "minecraft:block",
        base_state_id: 15141,
        default_state_id: 15141,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:tube_coral_block",
        block_type: "minecraft:coral",
        base_state_id: 15142,
        default_state_id: 15142,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brain_coral_block",
        block_type: "minecraft:coral",
        base_state_id: 15143,
        default_state_id: 15143,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:bubble_coral_block",
        block_type: "minecraft:coral",
        base_state_id: 15144,
        default_state_id: 15144,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:fire_coral_block",
        block_type: "minecraft:coral",
        base_state_id: 15145,
        default_state_id: 15145,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:horn_coral_block",
        block_type: "minecraft:coral",
        base_state_id: 15146,
        default_state_id: 15146,
        properties: EMPTY,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_tube_coral",
        block_type: "minecraft:base_coral_plant",
        base_state_id: 15147,
        default_state_id: 15147,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_brain_coral",
        block_type: "minecraft:base_coral_plant",
        base_state_id: 15149,
        default_state_id: 15149,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_bubble_coral",
        block_type: "minecraft:base_coral_plant",
        base_state_id: 15151,
        default_state_id: 15151,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_fire_coral",
        block_type: "minecraft:base_coral_plant",
        base_state_id: 15153,
        default_state_id: 15153,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_horn_coral",
        block_type: "minecraft:base_coral_plant",
        base_state_id: 15155,
        default_state_id: 15155,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:tube_coral",
        block_type: "minecraft:coral_plant",
        base_state_id: 15157,
        default_state_id: 15157,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brain_coral",
        block_type: "minecraft:coral_plant",
        base_state_id: 15159,
        default_state_id: 15159,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:bubble_coral",
        block_type: "minecraft:coral_plant",
        base_state_id: 15161,
        default_state_id: 15161,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:fire_coral",
        block_type: "minecraft:coral_plant",
        base_state_id: 15163,
        default_state_id: 15163,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:horn_coral",
        block_type: "minecraft:coral_plant",
        base_state_id: 15165,
        default_state_id: 15165,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_tube_coral_fan",
        block_type: "minecraft:base_coral_fan",
        base_state_id: 15167,
        default_state_id: 15167,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_brain_coral_fan",
        block_type: "minecraft:base_coral_fan",
        base_state_id: 15169,
        default_state_id: 15169,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_bubble_coral_fan",
        block_type: "minecraft:base_coral_fan",
        base_state_id: 15171,
        default_state_id: 15171,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_fire_coral_fan",
        block_type: "minecraft:base_coral_fan",
        base_state_id: 15173,
        default_state_id: 15173,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_horn_coral_fan",
        block_type: "minecraft:base_coral_fan",
        base_state_id: 15175,
        default_state_id: 15175,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:tube_coral_fan",
        block_type: "minecraft:coral_fan",
        base_state_id: 15177,
        default_state_id: 15177,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:brain_coral_fan",
        block_type: "minecraft:coral_fan",
        base_state_id: 15179,
        default_state_id: 15179,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:bubble_coral_fan",
        block_type: "minecraft:coral_fan",
        base_state_id: 15181,
        default_state_id: 15181,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:fire_coral_fan",
        block_type: "minecraft:coral_fan",
        base_state_id: 15183,
        default_state_id: 15183,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:horn_coral_fan",
        block_type: "minecraft:coral_fan",
        base_state_id: 15185,
        default_state_id: 15185,
        properties: L6,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_tube_coral_wall_fan",
        block_type: "minecraft:base_coral_wall_fan",
        base_state_id: 15187,
        default_state_id: 15187,
        properties: L30,
    },
    BlockStateEntryData {
        registry_id: "minecraft:dead_brain_coral_wall_fan",
        block_type: "minecraft:base_coral_wall_fan",
        base_state_id: 15195,
        default_state_id: 15195,
        properties: L30,
    },
];
