export const configurationCompletionManifest = {
  protocolVersion: 775,
  finishConfigurationPacketId: 3,
  registryOrder: [
    'minecraft:worldgen/biome',
    'minecraft:chat_type',
    'minecraft:trim_pattern',
    'minecraft:trim_material',
    'minecraft:wolf_variant',
    'minecraft:wolf_sound_variant',
    'minecraft:pig_variant',
    'minecraft:pig_sound_variant',
    'minecraft:frog_variant',
    'minecraft:cat_variant',
    'minecraft:cat_sound_variant',
    'minecraft:cow_sound_variant',
    'minecraft:cow_variant',
    'minecraft:chicken_sound_variant',
    'minecraft:chicken_variant',
    'minecraft:zombie_nautilus_variant',
    'minecraft:painting_variant',
    'minecraft:dimension_type',
    'minecraft:damage_type',
    'minecraft:banner_pattern',
    'minecraft:jukebox_song',
    'minecraft:instrument',
    'minecraft:world_clock',
    'minecraft:timeline'
  ],
  elementCounts: {
    'minecraft:banner_pattern': 43,
    'minecraft:worldgen/biome': 65,
    'minecraft:cat_sound_variant': 2,
    'minecraft:cat_variant': 11,
    'minecraft:chat_type': 7,
    'minecraft:chicken_sound_variant': 2,
    'minecraft:chicken_variant': 3,
    'minecraft:cow_sound_variant': 2,
    'minecraft:cow_variant': 3,
    'minecraft:damage_type': 50,
    'minecraft:dimension_type': 4,
    'minecraft:frog_variant': 3,
    'minecraft:instrument': 8,
    'minecraft:jukebox_song': 21,
    'minecraft:painting_variant': 51,
    'minecraft:pig_sound_variant': 3,
    'minecraft:pig_variant': 3,
    'minecraft:timeline': 4,
    'minecraft:trim_material': 11,
    'minecraft:trim_pattern': 18,
    'minecraft:world_clock': 2,
    'minecraft:wolf_sound_variant': 7,
    'minecraft:wolf_variant': 9,
    'minecraft:zombie_nautilus_variant': 2
  },
  requiredElements: {
    'minecraft:banner_pattern': ['minecraft:bricks', 'minecraft:curly_border', 'minecraft:flower'],
    'minecraft:worldgen/biome': ['minecraft:end_barrens', 'minecraft:plains', 'minecraft:the_void'],
    'minecraft:cat_sound_variant': ['minecraft:classic', 'minecraft:royal'],
    'minecraft:chat_type': [
      'minecraft:chat',
      'minecraft:emote_command',
      'minecraft:msg_command_incoming',
      'minecraft:msg_command_outgoing',
      'minecraft:say_command',
      'minecraft:team_msg_command_incoming',
      'minecraft:team_msg_command_outgoing'
    ],
    'minecraft:chicken_sound_variant': ['minecraft:classic', 'minecraft:picky'],
    'minecraft:chicken_variant': ['minecraft:cold', 'minecraft:temperate', 'minecraft:warm'],
    'minecraft:cow_sound_variant': ['minecraft:classic', 'minecraft:moody'],
    'minecraft:damage_type': ['minecraft:spear'],
    'minecraft:dimension_type': ['minecraft:overworld', 'minecraft:overworld_caves', 'minecraft:the_end', 'minecraft:the_nether'],
    'minecraft:instrument': ['minecraft:ponder_goat_horn'],
    'minecraft:jukebox_song': [
      'minecraft:11',
      'minecraft:13',
      'minecraft:5',
      'minecraft:creator',
      'minecraft:creator_music_box',
      'minecraft:lava_chicken',
      'minecraft:precipice',
      'minecraft:tears'
    ],
    'minecraft:painting_variant': ['minecraft:alban', 'minecraft:kebab', 'minecraft:wither'],
    'minecraft:pig_sound_variant': ['minecraft:big', 'minecraft:classic', 'minecraft:mini'],
    'minecraft:trim_material': [
      'minecraft:amethyst',
      'minecraft:copper',
      'minecraft:diamond',
      'minecraft:emerald',
      'minecraft:gold',
      'minecraft:iron',
      'minecraft:lapis',
      'minecraft:netherite',
      'minecraft:quartz',
      'minecraft:redstone',
      'minecraft:resin'
    ],
    'minecraft:wolf_sound_variant': ['minecraft:angry', 'minecraft:big', 'minecraft:classic', 'minecraft:cute', 'minecraft:grumpy', 'minecraft:puglin', 'minecraft:sad'],
    'minecraft:zombie_nautilus_variant': ['minecraft:temperate', 'minecraft:warm']
  },
  requiredTags: {
    'minecraft:banner_pattern': {
      'minecraft:pattern_item/bordure_indented': [6],
      'minecraft:pattern_item/creeper': [4],
      'minecraft:pattern_item/field_masoned': [2],
      'minecraft:pattern_item/flower': [12],
      'minecraft:pattern_item/flow': [11],
      'minecraft:pattern_item/globe': [13],
      'minecraft:pattern_item/guster': [16],
      'minecraft:pattern_item/mojang': [21],
      'minecraft:pattern_item/piglin': [22],
      'minecraft:pattern_item/skull': [24]
    },
    'minecraft:damage_type': {
      'minecraft:bypasses_shield': [31, 22, 4, 6, 16, 18, 48, 5, 40, 10, 8, 17, 39, 27, 23, 32, 19, 36, 33, 2, 3, 7, 11, 13, 20, 21, 24, 25, 42],
      'minecraft:is_explosion': [15, 9, 35, 1],
      'minecraft:is_fire': [21, 3, 31, 24, 20, 46, 14]
    }
  },
  knownPacks: [
    { namespace: 'minecraft', id: 'core', version: '26.1.2' }
  ],
  playEntryPackets: [
    'clientbound/minecraft:login',
    'clientbound/minecraft:player_info_update',
    'clientbound/minecraft:change_difficulty',
    'clientbound/minecraft:player_abilities',
    'clientbound/minecraft:set_held_slot',
    'clientbound/minecraft:set_experience',
    'clientbound/minecraft:set_health',
    'clientbound/minecraft:container_set_content',
    'clientbound/minecraft:set_cursor_item',
    'clientbound/minecraft:set_time',
    'clientbound/minecraft:player_position',
    'clientbound/minecraft:initialize_border',
    'clientbound/minecraft:set_default_spawn_position',
    'clientbound/minecraft:set_chunk_cache_center',
    'clientbound/minecraft:set_chunk_cache_radius',
    'clientbound/minecraft:game_event',
    'clientbound/minecraft:game_event',
    'clientbound/minecraft:game_event',
    'clientbound/minecraft:game_event',
    'clientbound/minecraft:chunk_batch_start',
    'clientbound/minecraft:level_chunk_with_light',
    'clientbound/minecraft:chunk_batch_finished'
  ]
}
