use super::*;
use std::collections::BTreeSet;

#[test]
#[allow(clippy::too_many_lines)]
fn block_entity_registry_valid_blocks_match_java_26_1_2() {
    fn assert_type(
        ty: BlockEntityTypeId,
        key: &'static str,
        valid_blocks: &[&'static str],
        op_only_custom_data: bool,
    ) {
        let info = type_info(ty);
        assert_eq!(info.key, key);
        assert_eq!(info.op_only_custom_data, op_only_custom_data, "{key}");

        let actual: BTreeSet<&'static str> = info.valid_blocks.iter().copied().collect();
        let expected: BTreeSet<&'static str> = valid_blocks.iter().copied().collect();
        assert_eq!(actual, expected, "{key}");
        assert_eq!(
            info.valid_blocks.len(),
            expected.len(),
            "{key} has duplicate valid block entries"
        );
    }

    assert_type(
        BlockEntityTypeId::Furnace,
        "furnace",
        &["minecraft:furnace"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Chest,
        "chest",
        &[
            "minecraft:chest",
            "minecraft:copper_chest",
            "minecraft:exposed_copper_chest",
            "minecraft:weathered_copper_chest",
            "minecraft:oxidized_copper_chest",
            "minecraft:waxed_copper_chest",
            "minecraft:waxed_exposed_copper_chest",
            "minecraft:waxed_weathered_copper_chest",
            "minecraft:waxed_oxidized_copper_chest",
        ],
        false,
    );
    assert_type(
        BlockEntityTypeId::TrappedChest,
        "trapped_chest",
        &["minecraft:trapped_chest"],
        false,
    );
    assert_type(
        BlockEntityTypeId::EnderChest,
        "ender_chest",
        &["minecraft:ender_chest"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Jukebox,
        "jukebox",
        &["minecraft:jukebox"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Dispenser,
        "dispenser",
        &["minecraft:dispenser"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Dropper,
        "dropper",
        &["minecraft:dropper"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Sign,
        "sign",
        &[
            "minecraft:oak_sign",
            "minecraft:spruce_sign",
            "minecraft:birch_sign",
            "minecraft:acacia_sign",
            "minecraft:cherry_sign",
            "minecraft:jungle_sign",
            "minecraft:dark_oak_sign",
            "minecraft:pale_oak_sign",
            "minecraft:oak_wall_sign",
            "minecraft:spruce_wall_sign",
            "minecraft:birch_wall_sign",
            "minecraft:acacia_wall_sign",
            "minecraft:cherry_wall_sign",
            "minecraft:jungle_wall_sign",
            "minecraft:dark_oak_wall_sign",
            "minecraft:pale_oak_wall_sign",
            "minecraft:crimson_sign",
            "minecraft:crimson_wall_sign",
            "minecraft:warped_sign",
            "minecraft:warped_wall_sign",
            "minecraft:mangrove_sign",
            "minecraft:mangrove_wall_sign",
            "minecraft:bamboo_sign",
            "minecraft:bamboo_wall_sign",
        ],
        true,
    );
    assert_type(
        BlockEntityTypeId::HangingSign,
        "hanging_sign",
        &[
            "minecraft:oak_hanging_sign",
            "minecraft:spruce_hanging_sign",
            "minecraft:birch_hanging_sign",
            "minecraft:acacia_hanging_sign",
            "minecraft:cherry_hanging_sign",
            "minecraft:jungle_hanging_sign",
            "minecraft:dark_oak_hanging_sign",
            "minecraft:pale_oak_hanging_sign",
            "minecraft:crimson_hanging_sign",
            "minecraft:warped_hanging_sign",
            "minecraft:mangrove_hanging_sign",
            "minecraft:bamboo_hanging_sign",
            "minecraft:oak_wall_hanging_sign",
            "minecraft:spruce_wall_hanging_sign",
            "minecraft:birch_wall_hanging_sign",
            "minecraft:acacia_wall_hanging_sign",
            "minecraft:cherry_wall_hanging_sign",
            "minecraft:jungle_wall_hanging_sign",
            "minecraft:dark_oak_wall_hanging_sign",
            "minecraft:pale_oak_wall_hanging_sign",
            "minecraft:crimson_wall_hanging_sign",
            "minecraft:warped_wall_hanging_sign",
            "minecraft:mangrove_wall_hanging_sign",
            "minecraft:bamboo_wall_hanging_sign",
        ],
        true,
    );
    assert_type(
        BlockEntityTypeId::MobSpawner,
        "mob_spawner",
        &["minecraft:spawner"],
        true,
    );
    assert_type(
        BlockEntityTypeId::CreakingHeart,
        "creaking_heart",
        &["minecraft:creaking_heart"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Piston,
        "piston",
        &["minecraft:moving_piston"],
        false,
    );
    assert_type(
        BlockEntityTypeId::BrewingStand,
        "brewing_stand",
        &["minecraft:brewing_stand"],
        false,
    );
    assert_type(
        BlockEntityTypeId::EnchantingTable,
        "enchanting_table",
        &["minecraft:enchanting_table"],
        false,
    );
    assert_type(
        BlockEntityTypeId::EndPortal,
        "end_portal",
        &["minecraft:end_portal"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Beacon,
        "beacon",
        &["minecraft:beacon"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Skull,
        "skull",
        &[
            "minecraft:skeleton_skull",
            "minecraft:skeleton_wall_skull",
            "minecraft:creeper_head",
            "minecraft:creeper_wall_head",
            "minecraft:dragon_head",
            "minecraft:dragon_wall_head",
            "minecraft:zombie_head",
            "minecraft:zombie_wall_head",
            "minecraft:wither_skeleton_skull",
            "minecraft:wither_skeleton_wall_skull",
            "minecraft:player_head",
            "minecraft:player_wall_head",
            "minecraft:piglin_head",
            "minecraft:piglin_wall_head",
        ],
        false,
    );
    assert_type(
        BlockEntityTypeId::DaylightDetector,
        "daylight_detector",
        &["minecraft:daylight_detector"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Hopper,
        "hopper",
        &["minecraft:hopper"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Comparator,
        "comparator",
        &["minecraft:comparator"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Banner,
        "banner",
        &[
            "minecraft:white_banner",
            "minecraft:orange_banner",
            "minecraft:magenta_banner",
            "minecraft:light_blue_banner",
            "minecraft:yellow_banner",
            "minecraft:lime_banner",
            "minecraft:pink_banner",
            "minecraft:gray_banner",
            "minecraft:light_gray_banner",
            "minecraft:cyan_banner",
            "minecraft:purple_banner",
            "minecraft:blue_banner",
            "minecraft:brown_banner",
            "minecraft:green_banner",
            "minecraft:red_banner",
            "minecraft:black_banner",
            "minecraft:white_wall_banner",
            "minecraft:orange_wall_banner",
            "minecraft:magenta_wall_banner",
            "minecraft:light_blue_wall_banner",
            "minecraft:yellow_wall_banner",
            "minecraft:lime_wall_banner",
            "minecraft:pink_wall_banner",
            "minecraft:gray_wall_banner",
            "minecraft:light_gray_wall_banner",
            "minecraft:cyan_wall_banner",
            "minecraft:purple_wall_banner",
            "minecraft:blue_wall_banner",
            "minecraft:brown_wall_banner",
            "minecraft:green_wall_banner",
            "minecraft:red_wall_banner",
            "minecraft:black_wall_banner",
        ],
        false,
    );
    assert_type(
        BlockEntityTypeId::StructureBlock,
        "structure_block",
        &["minecraft:structure_block"],
        false,
    );
    assert_type(
        BlockEntityTypeId::EndGateway,
        "end_gateway",
        &["minecraft:end_gateway"],
        false,
    );
    assert_type(
        BlockEntityTypeId::CommandBlock,
        "command_block",
        &[
            "minecraft:command_block",
            "minecraft:chain_command_block",
            "minecraft:repeating_command_block",
        ],
        true,
    );
    assert_type(
        BlockEntityTypeId::ShulkerBox,
        "shulker_box",
        &[
            "minecraft:shulker_box",
            "minecraft:black_shulker_box",
            "minecraft:blue_shulker_box",
            "minecraft:brown_shulker_box",
            "minecraft:cyan_shulker_box",
            "minecraft:gray_shulker_box",
            "minecraft:green_shulker_box",
            "minecraft:light_blue_shulker_box",
            "minecraft:light_gray_shulker_box",
            "minecraft:lime_shulker_box",
            "minecraft:magenta_shulker_box",
            "minecraft:orange_shulker_box",
            "minecraft:pink_shulker_box",
            "minecraft:purple_shulker_box",
            "minecraft:red_shulker_box",
            "minecraft:white_shulker_box",
            "minecraft:yellow_shulker_box",
        ],
        false,
    );
    assert_type(
        BlockEntityTypeId::Bed,
        "bed",
        &[
            "minecraft:red_bed",
            "minecraft:black_bed",
            "minecraft:blue_bed",
            "minecraft:brown_bed",
            "minecraft:cyan_bed",
            "minecraft:gray_bed",
            "minecraft:green_bed",
            "minecraft:light_blue_bed",
            "minecraft:light_gray_bed",
            "minecraft:lime_bed",
            "minecraft:magenta_bed",
            "minecraft:orange_bed",
            "minecraft:pink_bed",
            "minecraft:purple_bed",
            "minecraft:white_bed",
            "minecraft:yellow_bed",
        ],
        false,
    );
    assert_type(
        BlockEntityTypeId::Conduit,
        "conduit",
        &["minecraft:conduit"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Barrel,
        "barrel",
        &["minecraft:barrel"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Smoker,
        "smoker",
        &["minecraft:smoker"],
        false,
    );
    assert_type(
        BlockEntityTypeId::BlastFurnace,
        "blast_furnace",
        &["minecraft:blast_furnace"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Lectern,
        "lectern",
        &["minecraft:lectern"],
        true,
    );
    assert_type(BlockEntityTypeId::Bell, "bell", &["minecraft:bell"], false);
    assert_type(
        BlockEntityTypeId::Jigsaw,
        "jigsaw",
        &["minecraft:jigsaw"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Campfire,
        "campfire",
        &["minecraft:campfire", "minecraft:soul_campfire"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Beehive,
        "beehive",
        &["minecraft:bee_nest", "minecraft:beehive"],
        false,
    );
    assert_type(
        BlockEntityTypeId::SculkSensor,
        "sculk_sensor",
        &["minecraft:sculk_sensor"],
        false,
    );
    assert_type(
        BlockEntityTypeId::CalibratedSculkSensor,
        "calibrated_sculk_sensor",
        &["minecraft:calibrated_sculk_sensor"],
        false,
    );
    assert_type(
        BlockEntityTypeId::SculkCatalyst,
        "sculk_catalyst",
        &["minecraft:sculk_catalyst"],
        false,
    );
    assert_type(
        BlockEntityTypeId::SculkShrieker,
        "sculk_shrieker",
        &["minecraft:sculk_shrieker"],
        false,
    );
    assert_type(
        BlockEntityTypeId::ChiseledBookshelf,
        "chiseled_bookshelf",
        &["minecraft:chiseled_bookshelf"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Shelf,
        "shelf",
        &[
            "minecraft:acacia_shelf",
            "minecraft:bamboo_shelf",
            "minecraft:birch_shelf",
            "minecraft:cherry_shelf",
            "minecraft:crimson_shelf",
            "minecraft:dark_oak_shelf",
            "minecraft:jungle_shelf",
            "minecraft:mangrove_shelf",
            "minecraft:oak_shelf",
            "minecraft:pale_oak_shelf",
            "minecraft:spruce_shelf",
            "minecraft:warped_shelf",
        ],
        false,
    );
    assert_type(
        BlockEntityTypeId::BrushableBlock,
        "brushable_block",
        &["minecraft:suspicious_sand", "minecraft:suspicious_gravel"],
        false,
    );
    assert_type(
        BlockEntityTypeId::DecoratedPot,
        "decorated_pot",
        &["minecraft:decorated_pot"],
        false,
    );
    assert_type(
        BlockEntityTypeId::Crafter,
        "crafter",
        &["minecraft:crafter"],
        false,
    );
    assert_type(
        BlockEntityTypeId::TrialSpawner,
        "trial_spawner",
        &["minecraft:trial_spawner"],
        true,
    );
    assert_type(
        BlockEntityTypeId::Vault,
        "vault",
        &["minecraft:vault"],
        false,
    );
    assert_type(
        BlockEntityTypeId::TestBlock,
        "test_block",
        &["minecraft:test_block"],
        false,
    );
    assert_type(
        BlockEntityTypeId::TestInstanceBlock,
        "test_instance_block",
        &["minecraft:test_instance_block"],
        false,
    );
    assert_type(
        BlockEntityTypeId::CopperGolemStatue,
        "copper_golem_statue",
        &[
            "minecraft:copper_golem_statue",
            "minecraft:exposed_copper_golem_statue",
            "minecraft:weathered_copper_golem_statue",
            "minecraft:oxidized_copper_golem_statue",
            "minecraft:waxed_copper_golem_statue",
            "minecraft:waxed_exposed_copper_golem_statue",
            "minecraft:waxed_weathered_copper_golem_statue",
            "minecraft:waxed_oxidized_copper_golem_statue",
        ],
        false,
    );
}
