use super::*;

pub const NETHER_WASTES_FEATURE_STEPS: &[&[&str]] = &[
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[
        "minecraft:spring_open",
        "minecraft:patch_fire",
        "minecraft:patch_soul_fire",
        "minecraft:glowstone_extra",
        "minecraft:glowstone",
        "minecraft:brown_mushroom_nether",
        "minecraft:red_mushroom_nether",
        "minecraft:ore_magma",
        "minecraft:spring_closed",
        "minecraft:ore_gravel_nether",
        "minecraft:ore_blackstone",
        "minecraft:ore_gold_nether",
        "minecraft:ore_quartz_nether",
        "minecraft:ore_ancient_debris_large",
        "minecraft:ore_debris_small",
    ],
    &[],
    &[
        "minecraft:spring_lava",
        "minecraft:brown_mushroom_normal",
        "minecraft:red_mushroom_normal",
    ],
];

pub const CRIMSON_FOREST_FEATURE_STEPS: &[&[&str]] = &[
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[
        "minecraft:spring_open",
        "minecraft:patch_fire",
        "minecraft:glowstone_extra",
        "minecraft:glowstone",
        "minecraft:ore_magma",
        "minecraft:spring_closed",
        "minecraft:ore_gravel_nether",
        "minecraft:ore_blackstone",
        "minecraft:ore_gold_nether",
        "minecraft:ore_quartz_nether",
        "minecraft:ore_ancient_debris_large",
        "minecraft:ore_debris_small",
    ],
    &[],
    &[
        "minecraft:spring_lava",
        "minecraft:brown_mushroom_normal",
        "minecraft:red_mushroom_normal",
        "minecraft:weeping_vines",
        "minecraft:crimson_fungi",
        "minecraft:crimson_forest_vegetation",
    ],
];

pub const WARPED_FOREST_FEATURE_STEPS: &[&[&str]] = &[
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[
        "minecraft:spring_open",
        "minecraft:patch_fire",
        "minecraft:patch_soul_fire",
        "minecraft:glowstone_extra",
        "minecraft:glowstone",
        "minecraft:ore_magma",
        "minecraft:spring_closed",
        "minecraft:ore_gravel_nether",
        "minecraft:ore_blackstone",
        "minecraft:ore_gold_nether",
        "minecraft:ore_quartz_nether",
        "minecraft:ore_ancient_debris_large",
        "minecraft:ore_debris_small",
    ],
    &[],
    &[
        "minecraft:spring_lava",
        "minecraft:brown_mushroom_normal",
        "minecraft:red_mushroom_normal",
        "minecraft:warped_fungi",
        "minecraft:warped_forest_vegetation",
        "minecraft:nether_sprouts",
        "minecraft:twisting_vines",
    ],
];

pub const SOUL_SAND_VALLEY_FEATURE_STEPS: &[&[&str]] = &[
    &[],
    &[],
    &["minecraft:basalt_pillar"],
    &[],
    &[],
    &[],
    &[],
    &[
        "minecraft:spring_open",
        "minecraft:patch_fire",
        "minecraft:patch_soul_fire",
        "minecraft:glowstone_extra",
        "minecraft:glowstone",
        "minecraft:patch_crimson_roots",
        "minecraft:ore_magma",
        "minecraft:spring_closed",
        "minecraft:ore_soul_sand",
        "minecraft:ore_gravel_nether",
        "minecraft:ore_blackstone",
        "minecraft:ore_gold_nether",
        "minecraft:ore_quartz_nether",
        "minecraft:ore_ancient_debris_large",
        "minecraft:ore_debris_small",
    ],
    &[],
    &["minecraft:spring_lava"],
];

pub const BASALT_DELTAS_FEATURE_STEPS: &[&[&str]] = &[
    &[],
    &[],
    &[],
    &[],
    &[
        "minecraft:delta",
        "minecraft:small_basalt_columns",
        "minecraft:large_basalt_columns",
    ],
    &[],
    &[],
    &[
        "minecraft:basalt_blobs",
        "minecraft:blackstone_blobs",
        "minecraft:spring_delta",
        "minecraft:patch_fire",
        "minecraft:patch_soul_fire",
        "minecraft:glowstone_extra",
        "minecraft:glowstone",
        "minecraft:brown_mushroom_nether",
        "minecraft:red_mushroom_nether",
        "minecraft:ore_magma",
        "minecraft:spring_closed_double",
        "minecraft:ore_gold_deltas",
        "minecraft:ore_quartz_deltas",
        "minecraft:ore_ancient_debris_large",
        "minecraft:ore_debris_small",
    ],
];

pub const THE_END_FEATURE_STEPS: &[&[&str]] = &[
    &[],
    &[],
    &[],
    &[],
    &["minecraft:end_spike"],
    &[],
    &[],
    &[],
    &[],
    &[],
    &["minecraft:end_platform"],
];

pub const THE_VOID_FEATURE_STEPS: &[&[&str]] = &[
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &["minecraft:void_start_platform"],
];

pub const END_HIGHLANDS_FEATURE_STEPS: &[&[&str]] = &[
    &[],
    &[],
    &[],
    &[],
    &["minecraft:end_gateway_return"],
    &[],
    &[],
    &[],
    &[],
    &["minecraft:chorus_plant"],
];

pub const END_MIDLANDS_FEATURE_STEPS: &[&[&str]] = &[];
pub const SMALL_END_ISLANDS_FEATURE_STEPS: &[&[&str]] = &[&["minecraft:end_island_decorated"]];
pub const END_BARRENS_FEATURE_STEPS: &[&[&str]] = &[];

