use super::*;

pub const BUILTIN_BIOME_GENERATION_SETTINGS: &[BiomeGenerationSettingsModel] = &[
    BiomeGenerationSettingsModel {
        biome: "minecraft:the_void",
        carvers: &[],
        feature_steps: THE_VOID_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: THE_VOID_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:plains",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: PLAINS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: PLAINS_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:sunflower_plains",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: SUNFLOWER_PLAINS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: PLAINS_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:forest",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: FOREST_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: FOREST_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:birch_forest",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: BIRCH_FOREST_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: BIRCH_FOREST_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:old_growth_birch_forest",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: OLD_GROWTH_BIRCH_FOREST_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: BIRCH_FOREST_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:dark_forest",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: DARK_FOREST_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: BIRCH_FOREST_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:flower_forest",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: FLOWER_FOREST_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: FLOWER_FOREST_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:river",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: RIVER_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: RIVER_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:frozen_river",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: FROZEN_RIVER_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: FROZEN_RIVER_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:ocean",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: OCEAN_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: OCEAN_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:deep_ocean",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: DEEP_OCEAN_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: OCEAN_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:cold_ocean",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: COLD_OCEAN_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: COLD_OCEAN_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:deep_cold_ocean",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: DEEP_COLD_OCEAN_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: COLD_OCEAN_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:lukewarm_ocean",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: LUKEWARM_OCEAN_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: LUKEWARM_OCEAN_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:deep_lukewarm_ocean",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: DEEP_LUKEWARM_OCEAN_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: DEEP_LUKEWARM_OCEAN_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:warm_ocean",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: WARM_OCEAN_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: WARM_OCEAN_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:deep_frozen_ocean",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: DEEP_FROZEN_OCEAN_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: DEEP_FROZEN_OCEAN_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:frozen_ocean",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: DEEP_FROZEN_OCEAN_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: DEEP_FROZEN_OCEAN_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:beach",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: BEACH_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: BEACH_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:snowy_beach",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: SNOWY_BEACH_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: SNOWY_BEACH_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:stony_shore",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: STONY_SHORE_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: SNOWY_BEACH_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:mushroom_fields",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: MUSHROOM_FIELDS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: MUSHROOM_FIELDS_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:badlands",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: BADLANDS_FEATURE_STEPS,
        creature_spawn_probability: 0.03,
        spawn_costs: &[],
        spawners: BADLANDS_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:eroded_badlands",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: BADLANDS_FEATURE_STEPS,
        creature_spawn_probability: 0.03,
        spawn_costs: &[],
        spawners: BADLANDS_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:wooded_badlands",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: WOODED_BADLANDS_FEATURE_STEPS,
        creature_spawn_probability: 0.04,
        spawn_costs: &[],
        spawners: WOODED_BADLANDS_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:meadow",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: MEADOW_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: MEADOW_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:cherry_grove",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: CHERRY_GROVE_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: CHERRY_GROVE_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:pale_garden",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: PALE_GARDEN_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: PALE_GARDEN_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:lush_caves",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: LUSH_CAVES_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: LUSH_CAVES_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:dripstone_caves",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: DRIPSTONE_CAVES_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: DRIPSTONE_CAVES_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:deep_dark",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: DEEP_DARK_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: DEEP_DARK_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:nether_wastes",
        carvers: NETHER_COMMON_CARVERS,
        feature_steps: NETHER_WASTES_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: NETHER_WASTES_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:crimson_forest",
        carvers: NETHER_COMMON_CARVERS,
        feature_steps: CRIMSON_FOREST_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: CRIMSON_FOREST_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:warped_forest",
        carvers: NETHER_COMMON_CARVERS,
        feature_steps: WARPED_FOREST_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: WARPED_FOREST_SPAWN_COSTS,
        spawners: WARPED_FOREST_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:soul_sand_valley",
        carvers: NETHER_COMMON_CARVERS,
        feature_steps: SOUL_SAND_VALLEY_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: SOUL_SAND_VALLEY_SPAWN_COSTS,
        spawners: SOUL_SAND_VALLEY_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:basalt_deltas",
        carvers: NETHER_COMMON_CARVERS,
        feature_steps: BASALT_DELTAS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: BASALT_DELTAS_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:the_end",
        carvers: &[],
        feature_steps: THE_END_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: END_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:end_highlands",
        carvers: &[],
        feature_steps: END_HIGHLANDS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: END_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:end_midlands",
        carvers: &[],
        feature_steps: END_MIDLANDS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: END_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:small_end_islands",
        carvers: &[],
        feature_steps: SMALL_END_ISLANDS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: END_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:end_barrens",
        carvers: &[],
        feature_steps: END_BARRENS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: END_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:grove",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: GROVE_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: GROVE_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:snowy_slopes",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: SNOWY_SLOPES_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: SNOWY_SLOPES_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:frozen_peaks",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: FROZEN_PEAKS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: FROZEN_PEAKS_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:jagged_peaks",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: FROZEN_PEAKS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: FROZEN_PEAKS_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:stony_peaks",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: STONY_PEAKS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: STONY_PEAKS_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:windswept_hills",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: WINDSWEPT_HILLS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: WINDSWEPT_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:windswept_gravelly_hills",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: WINDSWEPT_HILLS_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: WINDSWEPT_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:windswept_forest",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: WINDSWEPT_FOREST_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: WINDSWEPT_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:desert",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: DESERT_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: DESERT_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:savanna",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: SAVANNA_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: SAVANNA_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:savanna_plateau",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: SAVANNA_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: SAVANNA_PLATEAU_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:windswept_savanna",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: WINDSWEPT_SAVANNA_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: SAVANNA_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:taiga",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: TAIGA_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: TAIGA_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:snowy_taiga",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: SNOWY_TAIGA_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: TAIGA_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:old_growth_pine_taiga",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: OLD_GROWTH_PINE_TAIGA_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: OLD_GROWTH_PINE_TAIGA_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:old_growth_spruce_taiga",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: OLD_GROWTH_SPRUCE_TAIGA_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: TAIGA_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:snowy_plains",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: SNOWY_PLAINS_FEATURE_STEPS,
        creature_spawn_probability: 0.07,
        spawn_costs: &[],
        spawners: SNOWY_PLAINS_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:ice_spikes",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: ICE_SPIKES_FEATURE_STEPS,
        creature_spawn_probability: 0.07,
        spawn_costs: &[],
        spawners: SNOWY_PLAINS_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:jungle",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: JUNGLE_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: JUNGLE_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:sparse_jungle",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: SPARSE_JUNGLE_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: SPARSE_JUNGLE_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:bamboo_jungle",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: BAMBOO_JUNGLE_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: BAMBOO_JUNGLE_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:swamp",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: SWAMP_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: SWAMP_SPAWNER_GROUPS,
    },
    BiomeGenerationSettingsModel {
        biome: "minecraft:mangrove_swamp",
        carvers: OVERWORLD_COMMON_CARVERS,
        feature_steps: MANGROVE_SWAMP_FEATURE_STEPS,
        creature_spawn_probability: 0.1,
        spawn_costs: &[],
        spawners: MANGROVE_SWAMP_SPAWNER_GROUPS,
    },
];

