use super::*;

pub const FEATURE_TYPES: &[FeatureType] = &[
    feature_type(
        "minecraft:no_op",
        FeatureConfigurationKind::None,
        FeatureFamily::Selector,
    ),
    feature_type(
        "minecraft:tree",
        FeatureConfigurationKind::Tree,
        FeatureFamily::Tree,
    ),
    feature_type(
        "minecraft:fallen_tree",
        FeatureConfigurationKind::FallenTree,
        FeatureFamily::Tree,
    ),
    feature_type(
        "minecraft:block_pile",
        FeatureConfigurationKind::BlockPile,
        FeatureFamily::BlockPlacement,
    ),
    feature_type(
        "minecraft:spring_feature",
        FeatureConfigurationKind::Spring,
        FeatureFamily::Cave,
    ),
    feature_type(
        "minecraft:chorus_plant",
        FeatureConfigurationKind::None,
        FeatureFamily::End,
    ),
    feature_type(
        "minecraft:replace_single_block",
        FeatureConfigurationKind::ReplaceBlock,
        FeatureFamily::BlockPlacement,
    ),
    feature_type(
        "minecraft:void_start_platform",
        FeatureConfigurationKind::None,
        FeatureFamily::End,
    ),
    feature_type(
        "minecraft:desert_well",
        FeatureConfigurationKind::None,
        FeatureFamily::StructureLike,
    ),
    feature_type(
        "minecraft:fossil",
        FeatureConfigurationKind::Fossil,
        FeatureFamily::StructureLike,
    ),
    feature_type(
        "minecraft:huge_red_mushroom",
        FeatureConfigurationKind::HugeMushroom,
        FeatureFamily::Vegetation,
    ),
    feature_type(
        "minecraft:huge_brown_mushroom",
        FeatureConfigurationKind::HugeMushroom,
        FeatureFamily::Vegetation,
    ),
    feature_type(
        "minecraft:spike",
        FeatureConfigurationKind::Spike,
        FeatureFamily::End,
    ),
    feature_type(
        "minecraft:glowstone_blob",
        FeatureConfigurationKind::None,
        FeatureFamily::Nether,
    ),
    feature_type(
        "minecraft:freeze_top_layer",
        FeatureConfigurationKind::None,
        FeatureFamily::BlockPlacement,
    ),
    feature_type(
        "minecraft:vines",
        FeatureConfigurationKind::None,
        FeatureFamily::Vegetation,
    ),
    feature_type(
        "minecraft:block_column",
        FeatureConfigurationKind::BlockColumn,
        FeatureFamily::BlockPlacement,
    ),
    feature_type(
        "minecraft:vegetation_patch",
        FeatureConfigurationKind::VegetationPatch,
        FeatureFamily::Vegetation,
    ),
    feature_type(
        "minecraft:waterlogged_vegetation_patch",
        FeatureConfigurationKind::VegetationPatch,
        FeatureFamily::Vegetation,
    ),
    feature_type(
        "minecraft:root_system",
        FeatureConfigurationKind::RootSystem,
        FeatureFamily::Tree,
    ),
    feature_type(
        "minecraft:multiface_growth",
        FeatureConfigurationKind::MultifaceGrowth,
        FeatureFamily::Vegetation,
    ),
    feature_type(
        "minecraft:underwater_magma",
        FeatureConfigurationKind::UnderwaterMagma,
        FeatureFamily::Aquatic,
    ),
    feature_type(
        "minecraft:monster_room",
        FeatureConfigurationKind::None,
        FeatureFamily::StructureLike,
    ),
    feature_type(
        "minecraft:blue_ice",
        FeatureConfigurationKind::None,
        FeatureFamily::BlockPlacement,
    ),
    feature_type(
        "minecraft:iceberg",
        FeatureConfigurationKind::BlockState,
        FeatureFamily::Aquatic,
    ),
    feature_type(
        "minecraft:block_blob",
        FeatureConfigurationKind::BlockBlob,
        FeatureFamily::BlockPlacement,
    ),
    feature_type(
        "minecraft:disk",
        FeatureConfigurationKind::Disk,
        FeatureFamily::Disk,
    ),
    feature_type(
        "minecraft:lake",
        FeatureConfigurationKind::Lake,
        FeatureFamily::Lake,
    ),
    feature_type(
        "minecraft:ore",
        FeatureConfigurationKind::Ore,
        FeatureFamily::Ore,
    ),
    feature_type(
        "minecraft:end_platform",
        FeatureConfigurationKind::None,
        FeatureFamily::End,
    ),
    feature_type(
        "minecraft:end_spike",
        FeatureConfigurationKind::EndSpike,
        FeatureFamily::End,
    ),
    feature_type(
        "minecraft:end_island",
        FeatureConfigurationKind::None,
        FeatureFamily::End,
    ),
    feature_type(
        "minecraft:end_gateway",
        FeatureConfigurationKind::EndGateway,
        FeatureFamily::End,
    ),
    feature_type(
        "minecraft:seagrass",
        FeatureConfigurationKind::Probability,
        FeatureFamily::Aquatic,
    ),
    feature_type(
        "minecraft:kelp",
        FeatureConfigurationKind::None,
        FeatureFamily::Aquatic,
    ),
    feature_type(
        "minecraft:coral_tree",
        FeatureConfigurationKind::None,
        FeatureFamily::Aquatic,
    ),
    feature_type(
        "minecraft:coral_mushroom",
        FeatureConfigurationKind::None,
        FeatureFamily::Aquatic,
    ),
    feature_type(
        "minecraft:coral_claw",
        FeatureConfigurationKind::None,
        FeatureFamily::Aquatic,
    ),
    feature_type(
        "minecraft:sea_pickle",
        FeatureConfigurationKind::Count,
        FeatureFamily::Aquatic,
    ),
    feature_type(
        "minecraft:simple_block",
        FeatureConfigurationKind::SimpleBlock,
        FeatureFamily::BlockPlacement,
    ),
    feature_type(
        "minecraft:bamboo",
        FeatureConfigurationKind::Probability,
        FeatureFamily::Vegetation,
    ),
    feature_type(
        "minecraft:huge_fungus",
        FeatureConfigurationKind::HugeFungus,
        FeatureFamily::Nether,
    ),
    feature_type(
        "minecraft:nether_forest_vegetation",
        FeatureConfigurationKind::NetherForestVegetation,
        FeatureFamily::Nether,
    ),
    feature_type(
        "minecraft:weeping_vines",
        FeatureConfigurationKind::None,
        FeatureFamily::Nether,
    ),
    feature_type(
        "minecraft:twisting_vines",
        FeatureConfigurationKind::TwistingVines,
        FeatureFamily::Nether,
    ),
    feature_type(
        "minecraft:basalt_columns",
        FeatureConfigurationKind::Column,
        FeatureFamily::Nether,
    ),
    feature_type(
        "minecraft:delta_feature",
        FeatureConfigurationKind::Delta,
        FeatureFamily::Nether,
    ),
    feature_type(
        "minecraft:netherrack_replace_blobs",
        FeatureConfigurationKind::ReplaceSphere,
        FeatureFamily::Nether,
    ),
    feature_type(
        "minecraft:fill_layer",
        FeatureConfigurationKind::Layer,
        FeatureFamily::BlockPlacement,
    ),
    feature_type(
        "minecraft:bonus_chest",
        FeatureConfigurationKind::None,
        FeatureFamily::StructureLike,
    ),
    feature_type(
        "minecraft:basalt_pillar",
        FeatureConfigurationKind::None,
        FeatureFamily::Nether,
    ),
    feature_type(
        "minecraft:scattered_ore",
        FeatureConfigurationKind::Ore,
        FeatureFamily::Ore,
    ),
    feature_type(
        "minecraft:random_selector",
        FeatureConfigurationKind::RandomFeature,
        FeatureFamily::Selector,
    ),
    feature_type(
        "minecraft:simple_random_selector",
        FeatureConfigurationKind::SimpleRandomFeature,
        FeatureFamily::Selector,
    ),
    feature_type(
        "minecraft:random_boolean_selector",
        FeatureConfigurationKind::RandomBooleanFeature,
        FeatureFamily::Selector,
    ),
    feature_type(
        "minecraft:geode",
        FeatureConfigurationKind::Geode,
        FeatureFamily::Cave,
    ),
    feature_type(
        "minecraft:dripstone_cluster",
        FeatureConfigurationKind::DripstoneCluster,
        FeatureFamily::Cave,
    ),
    feature_type(
        "minecraft:large_dripstone",
        FeatureConfigurationKind::LargeDripstone,
        FeatureFamily::Cave,
    ),
    feature_type(
        "minecraft:pointed_dripstone",
        FeatureConfigurationKind::PointedDripstone,
        FeatureFamily::Cave,
    ),
    feature_type(
        "minecraft:sculk_patch",
        FeatureConfigurationKind::SculkPatch,
        FeatureFamily::Cave,
    ),
];

