//! Lookup table extracted from the Java source of `schemas/V704.java` (generated data).

/// `V704.ITEM_TO_BLOCKENTITY`.
pub const ITEM_TO_BLOCK_ENTITY: &[(&str, &str)] = &[
    ("minecraft:furnace", "minecraft:furnace"),
    ("minecraft:lit_furnace", "minecraft:furnace"),
    ("minecraft:chest", "minecraft:chest"),
    ("minecraft:trapped_chest", "minecraft:chest"),
    ("minecraft:ender_chest", "minecraft:ender_chest"),
    ("minecraft:jukebox", "minecraft:jukebox"),
    ("minecraft:dispenser", "minecraft:dispenser"),
    ("minecraft:dropper", "minecraft:dropper"),
    ("minecraft:sign", "minecraft:sign"),
    ("minecraft:mob_spawner", "minecraft:mob_spawner"),
    ("minecraft:spawner", "minecraft:mob_spawner"),
    ("minecraft:noteblock", "minecraft:noteblock"),
    ("minecraft:brewing_stand", "minecraft:brewing_stand"),
    ("minecraft:enhanting_table", "minecraft:enchanting_table"),
    ("minecraft:command_block", "minecraft:command_block"),
    ("minecraft:beacon", "minecraft:beacon"),
    ("minecraft:skull", "minecraft:skull"),
    ("minecraft:daylight_detector", "minecraft:daylight_detector"),
    ("minecraft:hopper", "minecraft:hopper"),
    ("minecraft:banner", "minecraft:banner"),
    ("minecraft:flower_pot", "minecraft:flower_pot"),
    (
        "minecraft:repeating_command_block",
        "minecraft:command_block",
    ),
    ("minecraft:chain_command_block", "minecraft:command_block"),
    ("minecraft:shulker_box", "minecraft:shulker_box"),
    ("minecraft:white_shulker_box", "minecraft:shulker_box"),
    ("minecraft:orange_shulker_box", "minecraft:shulker_box"),
    ("minecraft:magenta_shulker_box", "minecraft:shulker_box"),
    ("minecraft:light_blue_shulker_box", "minecraft:shulker_box"),
    ("minecraft:yellow_shulker_box", "minecraft:shulker_box"),
    ("minecraft:lime_shulker_box", "minecraft:shulker_box"),
    ("minecraft:pink_shulker_box", "minecraft:shulker_box"),
    ("minecraft:gray_shulker_box", "minecraft:shulker_box"),
    ("minecraft:silver_shulker_box", "minecraft:shulker_box"),
    ("minecraft:cyan_shulker_box", "minecraft:shulker_box"),
    ("minecraft:purple_shulker_box", "minecraft:shulker_box"),
    ("minecraft:blue_shulker_box", "minecraft:shulker_box"),
    ("minecraft:brown_shulker_box", "minecraft:shulker_box"),
    ("minecraft:green_shulker_box", "minecraft:shulker_box"),
    ("minecraft:red_shulker_box", "minecraft:shulker_box"),
    ("minecraft:black_shulker_box", "minecraft:shulker_box"),
    ("minecraft:bed", "minecraft:bed"),
    ("minecraft:light_gray_shulker_box", "minecraft:shulker_box"),
    ("minecraft:banner", "minecraft:banner"),
    ("minecraft:white_banner", "minecraft:banner"),
    ("minecraft:orange_banner", "minecraft:banner"),
    ("minecraft:magenta_banner", "minecraft:banner"),
    ("minecraft:light_blue_banner", "minecraft:banner"),
    ("minecraft:yellow_banner", "minecraft:banner"),
    ("minecraft:lime_banner", "minecraft:banner"),
    ("minecraft:pink_banner", "minecraft:banner"),
    ("minecraft:gray_banner", "minecraft:banner"),
    ("minecraft:silver_banner", "minecraft:banner"),
    ("minecraft:light_gray_banner", "minecraft:banner"),
    ("minecraft:cyan_banner", "minecraft:banner"),
    ("minecraft:purple_banner", "minecraft:banner"),
    ("minecraft:blue_banner", "minecraft:banner"),
    ("minecraft:brown_banner", "minecraft:banner"),
    ("minecraft:green_banner", "minecraft:banner"),
    ("minecraft:red_banner", "minecraft:banner"),
    ("minecraft:black_banner", "minecraft:banner"),
    ("minecraft:standing_sign", "minecraft:sign"),
    ("minecraft:wall_sign", "minecraft:sign"),
    ("minecraft:piston_head", "minecraft:piston"),
    (
        "minecraft:daylight_detector_inverted",
        "minecraft:daylight_detector",
    ),
    ("minecraft:unpowered_comparator", "minecraft:comparator"),
    ("minecraft:powered_comparator", "minecraft:comparator"),
    ("minecraft:wall_banner", "minecraft:banner"),
    ("minecraft:standing_banner", "minecraft:banner"),
    ("minecraft:structure_block", "minecraft:structure_block"),
    ("minecraft:end_portal", "minecraft:end_portal"),
    ("minecraft:end_gateway", "minecraft:end_gateway"),
    ("minecraft:sign", "minecraft:sign"),
    ("minecraft:shield", "minecraft:banner"),
    ("minecraft:white_bed", "minecraft:bed"),
    ("minecraft:orange_bed", "minecraft:bed"),
    ("minecraft:magenta_bed", "minecraft:bed"),
    ("minecraft:light_blue_bed", "minecraft:bed"),
    ("minecraft:yellow_bed", "minecraft:bed"),
    ("minecraft:lime_bed", "minecraft:bed"),
    ("minecraft:pink_bed", "minecraft:bed"),
    ("minecraft:gray_bed", "minecraft:bed"),
    ("minecraft:silver_bed", "minecraft:bed"),
    ("minecraft:light_gray_bed", "minecraft:bed"),
    ("minecraft:cyan_bed", "minecraft:bed"),
    ("minecraft:purple_bed", "minecraft:bed"),
    ("minecraft:blue_bed", "minecraft:bed"),
    ("minecraft:brown_bed", "minecraft:bed"),
    ("minecraft:green_bed", "minecraft:bed"),
    ("minecraft:red_bed", "minecraft:bed"),
    ("minecraft:black_bed", "minecraft:bed"),
    ("minecraft:oak_sign", "minecraft:sign"),
    ("minecraft:spruce_sign", "minecraft:sign"),
    ("minecraft:birch_sign", "minecraft:sign"),
    ("minecraft:jungle_sign", "minecraft:sign"),
    ("minecraft:acacia_sign", "minecraft:sign"),
    ("minecraft:dark_oak_sign", "minecraft:sign"),
    ("minecraft:crimson_sign", "minecraft:sign"),
    ("minecraft:warped_sign", "minecraft:sign"),
    ("minecraft:skeleton_skull", "minecraft:skull"),
    ("minecraft:wither_skeleton_skull", "minecraft:skull"),
    ("minecraft:zombie_head", "minecraft:skull"),
    ("minecraft:player_head", "minecraft:skull"),
    ("minecraft:creeper_head", "minecraft:skull"),
    ("minecraft:dragon_head", "minecraft:skull"),
    ("minecraft:barrel", "minecraft:barrel"),
    ("minecraft:conduit", "minecraft:conduit"),
    ("minecraft:smoker", "minecraft:smoker"),
    ("minecraft:blast_furnace", "minecraft:blast_furnace"),
    ("minecraft:lectern", "minecraft:lectern"),
    ("minecraft:bell", "minecraft:bell"),
    ("minecraft:jigsaw", "minecraft:jigsaw"),
    ("minecraft:campfire", "minecraft:campfire"),
    ("minecraft:bee_nest", "minecraft:beehive"),
    ("minecraft:beehive", "minecraft:beehive"),
    ("minecraft:sculk_sensor", "minecraft:sculk_sensor"),
    ("minecraft:decorated_pot", "minecraft:decorated_pot"),
    ("minecraft:crafter", "minecraft:crafter"),
];
