//! Lookup table extracted from the Java source of `schemas/V705.java` (generated data).

/// `V705.ITEM_TO_ENTITY`.
pub const ITEM_TO_ENTITY: &[(&str, &str)] = &[
    ("minecraft:armor_stand", "minecraft:armor_stand"),
    ("minecraft:painting", "minecraft:painting"),
    ("minecraft:armadillo_spawn_egg", "minecraft:armadillo"),
    ("minecraft:allay_spawn_egg", "minecraft:allay"),
    ("minecraft:axolotl_spawn_egg", "minecraft:axolotl"),
    ("minecraft:bat_spawn_egg", "minecraft:bat"),
    ("minecraft:bee_spawn_egg", "minecraft:bee"),
    ("minecraft:blaze_spawn_egg", "minecraft:blaze"),
    ("minecraft:bogged_spawn_egg", "minecraft:bogged"),
    ("minecraft:breeze_spawn_egg", "minecraft:breeze"),
    ("minecraft:cat_spawn_egg", "minecraft:cat"),
    ("minecraft:camel_spawn_egg", "minecraft:camel"),
    ("minecraft:cave_spider_spawn_egg", "minecraft:cave_spider"),
    ("minecraft:chicken_spawn_egg", "minecraft:chicken"),
    ("minecraft:cod_spawn_egg", "minecraft:cod"),
    ("minecraft:cow_spawn_egg", "minecraft:cow"),
    ("minecraft:creeper_spawn_egg", "minecraft:creeper"),
    ("minecraft:dolphin_spawn_egg", "minecraft:dolphin"),
    ("minecraft:donkey_spawn_egg", "minecraft:donkey"),
    ("minecraft:drowned_spawn_egg", "minecraft:drowned"),
    (
        "minecraft:elder_guardian_spawn_egg",
        "minecraft:elder_guardian",
    ),
    ("minecraft:ender_dragon_spawn_egg", "minecraft:ender_dragon"),
    ("minecraft:enderman_spawn_egg", "minecraft:enderman"),
    ("minecraft:endermite_spawn_egg", "minecraft:endermite"),
    ("minecraft:evoker_spawn_egg", "minecraft:evoker"),
    ("minecraft:fox_spawn_egg", "minecraft:fox"),
    ("minecraft:frog_spawn_egg", "minecraft:frog"),
    ("minecraft:ghast_spawn_egg", "minecraft:ghast"),
    ("minecraft:glow_squid_spawn_egg", "minecraft:glow_squid"),
    ("minecraft:goat_spawn_egg", "minecraft:goat"),
    ("minecraft:guardian_spawn_egg", "minecraft:guardian"),
    ("minecraft:hoglin_spawn_egg", "minecraft:hoglin"),
    ("minecraft:horse_spawn_egg", "minecraft:horse"),
    ("minecraft:husk_spawn_egg", "minecraft:husk"),
    ("minecraft:iron_golem_spawn_egg", "minecraft:iron_golem"),
    ("minecraft:llama_spawn_egg", "minecraft:llama"),
    ("minecraft:magma_cube_spawn_egg", "minecraft:magma_cube"),
    ("minecraft:mooshroom_spawn_egg", "minecraft:mooshroom"),
    ("minecraft:mule_spawn_egg", "minecraft:mule"),
    ("minecraft:ocelot_spawn_egg", "minecraft:ocelot"),
    ("minecraft:panda_spawn_egg", "minecraft:panda"),
    ("minecraft:parrot_spawn_egg", "minecraft:parrot"),
    ("minecraft:phantom_spawn_egg", "minecraft:phantom"),
    ("minecraft:pig_spawn_egg", "minecraft:pig"),
    ("minecraft:piglin_spawn_egg", "minecraft:piglin"),
    ("minecraft:piglin_brute_spawn_egg", "minecraft:piglin_brute"),
    ("minecraft:pillager_spawn_egg", "minecraft:pillager"),
    ("minecraft:polar_bear_spawn_egg", "minecraft:polar_bear"),
    ("minecraft:pufferfish_spawn_egg", "minecraft:pufferfish"),
    ("minecraft:rabbit_spawn_egg", "minecraft:rabbit"),
    ("minecraft:ravager_spawn_egg", "minecraft:ravager"),
    ("minecraft:salmon_spawn_egg", "minecraft:salmon"),
    ("minecraft:sheep_spawn_egg", "minecraft:sheep"),
    ("minecraft:shulker_spawn_egg", "minecraft:shulker"),
    ("minecraft:silverfish_spawn_egg", "minecraft:silverfish"),
    ("minecraft:skeleton_spawn_egg", "minecraft:skeleton"),
    (
        "minecraft:skeleton_horse_spawn_egg",
        "minecraft:skeleton_horse",
    ),
    ("minecraft:slime_spawn_egg", "minecraft:slime"),
    ("minecraft:sniffer_spawn_egg", "minecraft:sniffer"),
    ("minecraft:snow_golem_spawn_egg", "minecraft:snow_golem"),
    ("minecraft:spider_spawn_egg", "minecraft:spider"),
    ("minecraft:squid_spawn_egg", "minecraft:squid"),
    ("minecraft:stray_spawn_egg", "minecraft:stray"),
    ("minecraft:strider_spawn_egg", "minecraft:strider"),
    ("minecraft:tadpole_spawn_egg", "minecraft:tadpole"),
    ("minecraft:trader_llama_spawn_egg", "minecraft:trader_llama"),
    (
        "minecraft:tropical_fish_spawn_egg",
        "minecraft:tropical_fish",
    ),
    ("minecraft:turtle_spawn_egg", "minecraft:turtle"),
    ("minecraft:vex_spawn_egg", "minecraft:vex"),
    ("minecraft:villager_spawn_egg", "minecraft:villager"),
    ("minecraft:vindicator_spawn_egg", "minecraft:vindicator"),
    (
        "minecraft:wandering_trader_spawn_egg",
        "minecraft:wandering_trader",
    ),
    ("minecraft:warden_spawn_egg", "minecraft:warden"),
    ("minecraft:witch_spawn_egg", "minecraft:witch"),
    ("minecraft:wither_spawn_egg", "minecraft:wither"),
    (
        "minecraft:wither_skeleton_spawn_egg",
        "minecraft:wither_skeleton",
    ),
    ("minecraft:wolf_spawn_egg", "minecraft:wolf"),
    ("minecraft:zoglin_spawn_egg", "minecraft:zoglin"),
    ("minecraft:zombie_spawn_egg", "minecraft:zombie"),
    ("minecraft:zombie_horse_spawn_egg", "minecraft:zombie_horse"),
    (
        "minecraft:zombie_villager_spawn_egg",
        "minecraft:zombie_villager",
    ),
    (
        "minecraft:zombified_piglin_spawn_egg",
        "minecraft:zombified_piglin",
    ),
    ("minecraft:item_frame", "minecraft:item_frame"),
    ("minecraft:boat", "minecraft:oak_boat"),
    ("minecraft:oak_boat", "minecraft:oak_boat"),
    ("minecraft:oak_chest_boat", "minecraft:oak_chest_boat"),
    ("minecraft:spruce_boat", "minecraft:spruce_boat"),
    ("minecraft:spruce_chest_boat", "minecraft:spruce_chest_boat"),
    ("minecraft:birch_boat", "minecraft:birch_boat"),
    ("minecraft:birch_chest_boat", "minecraft:birch_chest_boat"),
    ("minecraft:jungle_boat", "minecraft:jungle_boat"),
    ("minecraft:jungle_chest_boat", "minecraft:jungle_chest_boat"),
    ("minecraft:acacia_boat", "minecraft:acacia_boat"),
    ("minecraft:acacia_chest_boat", "minecraft:acacia_chest_boat"),
    ("minecraft:cherry_boat", "minecraft:cherry_boat"),
    ("minecraft:cherry_chest_boat", "minecraft:cherry_chest_boat"),
    ("minecraft:dark_oak_boat", "minecraft:dark_oak_boat"),
    (
        "minecraft:dark_oak_chest_boat",
        "minecraft:dark_oak_chest_boat",
    ),
    ("minecraft:mangrove_boat", "minecraft:mangrove_boat"),
    (
        "minecraft:mangrove_chest_boat",
        "minecraft:mangrove_chest_boat",
    ),
    ("minecraft:bamboo_raft", "minecraft:bamboo_raft"),
    ("minecraft:bamboo_chest_raft", "minecraft:bamboo_chest_raft"),
    ("minecraft:minecart", "minecraft:minecart"),
    ("minecraft:chest_minecart", "minecraft:chest_minecart"),
    ("minecraft:furnace_minecart", "minecraft:furnace_minecart"),
    ("minecraft:tnt_minecart", "minecraft:tnt_minecart"),
    ("minecraft:hopper_minecart", "minecraft:hopper_minecart"),
];
