use super::{block, BlockRegistryEntry};

pub(super) const ENTRIES: &[BlockRegistryEntry] = &[
    block(572, "CYAN_WALL_BANNER", "minecraft:cyan_wall_banner"),
    block(573, "PURPLE_WALL_BANNER", "minecraft:purple_wall_banner"),
    block(574, "BLUE_WALL_BANNER", "minecraft:blue_wall_banner"),
    block(575, "BROWN_WALL_BANNER", "minecraft:brown_wall_banner"),
    block(576, "GREEN_WALL_BANNER", "minecraft:green_wall_banner"),
    block(577, "RED_WALL_BANNER", "minecraft:red_wall_banner"),
    block(578, "BLACK_WALL_BANNER", "minecraft:black_wall_banner"),
    block(579, "RED_SANDSTONE", "minecraft:red_sandstone"),
    block(
        580,
        "CHISELED_RED_SANDSTONE",
        "minecraft:chiseled_red_sandstone",
    ),
    block(581, "CUT_RED_SANDSTONE", "minecraft:cut_red_sandstone"),
    block(
        582,
        "RED_SANDSTONE_STAIRS",
        "minecraft:red_sandstone_stairs",
    ),
    block(583, "OAK_SLAB", "minecraft:oak_slab"),
    block(584, "SPRUCE_SLAB", "minecraft:spruce_slab"),
    block(585, "BIRCH_SLAB", "minecraft:birch_slab"),
    block(586, "JUNGLE_SLAB", "minecraft:jungle_slab"),
    block(587, "ACACIA_SLAB", "minecraft:acacia_slab"),
    block(588, "CHERRY_SLAB", "minecraft:cherry_slab"),
    block(589, "DARK_OAK_SLAB", "minecraft:dark_oak_slab"),
    block(590, "PALE_OAK_SLAB", "minecraft:pale_oak_slab"),
    block(591, "MANGROVE_SLAB", "minecraft:mangrove_slab"),
    block(592, "BAMBOO_SLAB", "minecraft:bamboo_slab"),
    block(593, "BAMBOO_MOSAIC_SLAB", "minecraft:bamboo_mosaic_slab"),
    block(594, "STONE_SLAB", "minecraft:stone_slab"),
    block(595, "SMOOTH_STONE_SLAB", "minecraft:smooth_stone_slab"),
    block(596, "SANDSTONE_SLAB", "minecraft:sandstone_slab"),
    block(597, "CUT_SANDSTONE_SLAB", "minecraft:cut_sandstone_slab"),
    block(598, "PETRIFIED_OAK_SLAB", "minecraft:petrified_oak_slab"),
    block(599, "COBBLESTONE_SLAB", "minecraft:cobblestone_slab"),
    block(600, "BRICK_SLAB", "minecraft:brick_slab"),
    block(601, "STONE_BRICK_SLAB", "minecraft:stone_brick_slab"),
    block(602, "MUD_BRICK_SLAB", "minecraft:mud_brick_slab"),
    block(603, "NETHER_BRICK_SLAB", "minecraft:nether_brick_slab"),
    block(604, "QUARTZ_SLAB", "minecraft:quartz_slab"),
    block(605, "RED_SANDSTONE_SLAB", "minecraft:red_sandstone_slab"),
    block(
        606,
        "CUT_RED_SANDSTONE_SLAB",
        "minecraft:cut_red_sandstone_slab",
    ),
    block(607, "PURPUR_SLAB", "minecraft:purpur_slab"),
    block(608, "SMOOTH_STONE", "minecraft:smooth_stone"),
    block(609, "SMOOTH_SANDSTONE", "minecraft:smooth_sandstone"),
    block(610, "SMOOTH_QUARTZ", "minecraft:smooth_quartz"),
    block(
        611,
        "SMOOTH_RED_SANDSTONE",
        "minecraft:smooth_red_sandstone",
    ),
    block(612, "SPRUCE_FENCE_GATE", "minecraft:spruce_fence_gate"),
    block(613, "BIRCH_FENCE_GATE", "minecraft:birch_fence_gate"),
    block(614, "JUNGLE_FENCE_GATE", "minecraft:jungle_fence_gate"),
    block(615, "ACACIA_FENCE_GATE", "minecraft:acacia_fence_gate"),
    block(616, "CHERRY_FENCE_GATE", "minecraft:cherry_fence_gate"),
    block(617, "DARK_OAK_FENCE_GATE", "minecraft:dark_oak_fence_gate"),
    block(618, "PALE_OAK_FENCE_GATE", "minecraft:pale_oak_fence_gate"),
    block(619, "MANGROVE_FENCE_GATE", "minecraft:mangrove_fence_gate"),
    block(620, "BAMBOO_FENCE_GATE", "minecraft:bamboo_fence_gate"),
    block(621, "SPRUCE_FENCE", "minecraft:spruce_fence"),
    block(622, "BIRCH_FENCE", "minecraft:birch_fence"),
    block(623, "JUNGLE_FENCE", "minecraft:jungle_fence"),
    block(624, "ACACIA_FENCE", "minecraft:acacia_fence"),
    block(625, "CHERRY_FENCE", "minecraft:cherry_fence"),
    block(626, "DARK_OAK_FENCE", "minecraft:dark_oak_fence"),
    block(627, "PALE_OAK_FENCE", "minecraft:pale_oak_fence"),
    block(628, "MANGROVE_FENCE", "minecraft:mangrove_fence"),
    block(629, "BAMBOO_FENCE", "minecraft:bamboo_fence"),
    block(630, "SPRUCE_DOOR", "minecraft:spruce_door"),
    block(631, "BIRCH_DOOR", "minecraft:birch_door"),
    block(632, "JUNGLE_DOOR", "minecraft:jungle_door"),
    block(633, "ACACIA_DOOR", "minecraft:acacia_door"),
    block(634, "CHERRY_DOOR", "minecraft:cherry_door"),
    block(635, "DARK_OAK_DOOR", "minecraft:dark_oak_door"),
    block(636, "PALE_OAK_DOOR", "minecraft:pale_oak_door"),
    block(637, "MANGROVE_DOOR", "minecraft:mangrove_door"),
    block(638, "BAMBOO_DOOR", "minecraft:bamboo_door"),
    block(639, "END_ROD", "minecraft:end_rod"),
    block(640, "CHORUS_PLANT", "minecraft:chorus_plant"),
    block(641, "CHORUS_FLOWER", "minecraft:chorus_flower"),
    block(642, "PURPUR_BLOCK", "minecraft:purpur_block"),
    block(643, "PURPUR_PILLAR", "minecraft:purpur_pillar"),
    block(644, "PURPUR_STAIRS", "minecraft:purpur_stairs"),
    block(645, "END_STONE_BRICKS", "minecraft:end_stone_bricks"),
    block(646, "TORCHFLOWER_CROP", "minecraft:torchflower_crop"),
    block(647, "PITCHER_CROP", "minecraft:pitcher_crop"),
    block(648, "PITCHER_PLANT", "minecraft:pitcher_plant"),
    block(649, "BEETROOTS", "minecraft:beetroots"),
    block(650, "DIRT_PATH", "minecraft:dirt_path"),
    block(651, "END_GATEWAY", "minecraft:end_gateway"),
    block(
        652,
        "REPEATING_COMMAND_BLOCK",
        "minecraft:repeating_command_block",
    ),
    block(653, "CHAIN_COMMAND_BLOCK", "minecraft:chain_command_block"),
    block(654, "FROSTED_ICE", "minecraft:frosted_ice"),
    block(655, "MAGMA_BLOCK", "minecraft:magma_block"),
    block(656, "NETHER_WART_BLOCK", "minecraft:nether_wart_block"),
    block(657, "RED_NETHER_BRICKS", "minecraft:red_nether_bricks"),
    block(658, "BONE_BLOCK", "minecraft:bone_block"),
    block(659, "STRUCTURE_VOID", "minecraft:structure_void"),
    block(660, "OBSERVER", "minecraft:observer"),
    block(661, "SHULKER_BOX", "minecraft:shulker_box"),
    block(662, "WHITE_SHULKER_BOX", "minecraft:white_shulker_box"),
    block(663, "ORANGE_SHULKER_BOX", "minecraft:orange_shulker_box"),
    block(664, "MAGENTA_SHULKER_BOX", "minecraft:magenta_shulker_box"),
    block(
        665,
        "LIGHT_BLUE_SHULKER_BOX",
        "minecraft:light_blue_shulker_box",
    ),
    block(666, "YELLOW_SHULKER_BOX", "minecraft:yellow_shulker_box"),
    block(667, "LIME_SHULKER_BOX", "minecraft:lime_shulker_box"),
    block(668, "PINK_SHULKER_BOX", "minecraft:pink_shulker_box"),
    block(669, "GRAY_SHULKER_BOX", "minecraft:gray_shulker_box"),
    block(
        670,
        "LIGHT_GRAY_SHULKER_BOX",
        "minecraft:light_gray_shulker_box",
    ),
    block(671, "CYAN_SHULKER_BOX", "minecraft:cyan_shulker_box"),
    block(672, "PURPLE_SHULKER_BOX", "minecraft:purple_shulker_box"),
    block(673, "BLUE_SHULKER_BOX", "minecraft:blue_shulker_box"),
    block(674, "BROWN_SHULKER_BOX", "minecraft:brown_shulker_box"),
    block(675, "GREEN_SHULKER_BOX", "minecraft:green_shulker_box"),
    block(676, "RED_SHULKER_BOX", "minecraft:red_shulker_box"),
    block(677, "BLACK_SHULKER_BOX", "minecraft:black_shulker_box"),
    block(
        678,
        "WHITE_GLAZED_TERRACOTTA",
        "minecraft:white_glazed_terracotta",
    ),
    block(
        679,
        "ORANGE_GLAZED_TERRACOTTA",
        "minecraft:orange_glazed_terracotta",
    ),
    block(
        680,
        "MAGENTA_GLAZED_TERRACOTTA",
        "minecraft:magenta_glazed_terracotta",
    ),
    block(
        681,
        "LIGHT_BLUE_GLAZED_TERRACOTTA",
        "minecraft:light_blue_glazed_terracotta",
    ),
    block(
        682,
        "YELLOW_GLAZED_TERRACOTTA",
        "minecraft:yellow_glazed_terracotta",
    ),
    block(
        683,
        "LIME_GLAZED_TERRACOTTA",
        "minecraft:lime_glazed_terracotta",
    ),
    block(
        684,
        "PINK_GLAZED_TERRACOTTA",
        "minecraft:pink_glazed_terracotta",
    ),
    block(
        685,
        "GRAY_GLAZED_TERRACOTTA",
        "minecraft:gray_glazed_terracotta",
    ),
    block(
        686,
        "LIGHT_GRAY_GLAZED_TERRACOTTA",
        "minecraft:light_gray_glazed_terracotta",
    ),
    block(
        687,
        "CYAN_GLAZED_TERRACOTTA",
        "minecraft:cyan_glazed_terracotta",
    ),
    block(
        688,
        "PURPLE_GLAZED_TERRACOTTA",
        "minecraft:purple_glazed_terracotta",
    ),
    block(
        689,
        "BLUE_GLAZED_TERRACOTTA",
        "minecraft:blue_glazed_terracotta",
    ),
    block(
        690,
        "BROWN_GLAZED_TERRACOTTA",
        "minecraft:brown_glazed_terracotta",
    ),
    block(
        691,
        "GREEN_GLAZED_TERRACOTTA",
        "minecraft:green_glazed_terracotta",
    ),
    block(
        692,
        "RED_GLAZED_TERRACOTTA",
        "minecraft:red_glazed_terracotta",
    ),
    block(
        693,
        "BLACK_GLAZED_TERRACOTTA",
        "minecraft:black_glazed_terracotta",
    ),
    block(694, "WHITE_CONCRETE", "minecraft:white_concrete"),
    block(695, "ORANGE_CONCRETE", "minecraft:orange_concrete"),
    block(696, "MAGENTA_CONCRETE", "minecraft:magenta_concrete"),
    block(697, "LIGHT_BLUE_CONCRETE", "minecraft:light_blue_concrete"),
    block(698, "YELLOW_CONCRETE", "minecraft:yellow_concrete"),
    block(699, "LIME_CONCRETE", "minecraft:lime_concrete"),
    block(700, "PINK_CONCRETE", "minecraft:pink_concrete"),
    block(701, "GRAY_CONCRETE", "minecraft:gray_concrete"),
    block(702, "LIGHT_GRAY_CONCRETE", "minecraft:light_gray_concrete"),
    block(703, "CYAN_CONCRETE", "minecraft:cyan_concrete"),
    block(704, "PURPLE_CONCRETE", "minecraft:purple_concrete"),
    block(705, "BLUE_CONCRETE", "minecraft:blue_concrete"),
    block(706, "BROWN_CONCRETE", "minecraft:brown_concrete"),
    block(707, "GREEN_CONCRETE", "minecraft:green_concrete"),
    block(708, "RED_CONCRETE", "minecraft:red_concrete"),
    block(709, "BLACK_CONCRETE", "minecraft:black_concrete"),
    block(
        710,
        "WHITE_CONCRETE_POWDER",
        "minecraft:white_concrete_powder",
    ),
    block(
        711,
        "ORANGE_CONCRETE_POWDER",
        "minecraft:orange_concrete_powder",
    ),
    block(
        712,
        "MAGENTA_CONCRETE_POWDER",
        "minecraft:magenta_concrete_powder",
    ),
    block(
        713,
        "LIGHT_BLUE_CONCRETE_POWDER",
        "minecraft:light_blue_concrete_powder",
    ),
    block(
        714,
        "YELLOW_CONCRETE_POWDER",
        "minecraft:yellow_concrete_powder",
    ),
    block(
        715,
        "LIME_CONCRETE_POWDER",
        "minecraft:lime_concrete_powder",
    ),
    block(
        716,
        "PINK_CONCRETE_POWDER",
        "minecraft:pink_concrete_powder",
    ),
    block(
        717,
        "GRAY_CONCRETE_POWDER",
        "minecraft:gray_concrete_powder",
    ),
    block(
        718,
        "LIGHT_GRAY_CONCRETE_POWDER",
        "minecraft:light_gray_concrete_powder",
    ),
    block(
        719,
        "CYAN_CONCRETE_POWDER",
        "minecraft:cyan_concrete_powder",
    ),
    block(
        720,
        "PURPLE_CONCRETE_POWDER",
        "minecraft:purple_concrete_powder",
    ),
    block(
        721,
        "BLUE_CONCRETE_POWDER",
        "minecraft:blue_concrete_powder",
    ),
    block(
        722,
        "BROWN_CONCRETE_POWDER",
        "minecraft:brown_concrete_powder",
    ),
    block(
        723,
        "GREEN_CONCRETE_POWDER",
        "minecraft:green_concrete_powder",
    ),
    block(724, "RED_CONCRETE_POWDER", "minecraft:red_concrete_powder"),
    block(
        725,
        "BLACK_CONCRETE_POWDER",
        "minecraft:black_concrete_powder",
    ),
    block(726, "KELP", "minecraft:kelp"),
    block(727, "KELP_PLANT", "minecraft:kelp_plant"),
    block(728, "DRIED_KELP_BLOCK", "minecraft:dried_kelp_block"),
    block(729, "TURTLE_EGG", "minecraft:turtle_egg"),
    block(730, "SNIFFER_EGG", "minecraft:sniffer_egg"),
    block(731, "DRIED_GHAST", "minecraft:dried_ghast"),
    block(
        732,
        "DEAD_TUBE_CORAL_BLOCK",
        "minecraft:dead_tube_coral_block",
    ),
    block(
        733,
        "DEAD_BRAIN_CORAL_BLOCK",
        "minecraft:dead_brain_coral_block",
    ),
    block(
        734,
        "DEAD_BUBBLE_CORAL_BLOCK",
        "minecraft:dead_bubble_coral_block",
    ),
    block(
        735,
        "DEAD_FIRE_CORAL_BLOCK",
        "minecraft:dead_fire_coral_block",
    ),
    block(
        736,
        "DEAD_HORN_CORAL_BLOCK",
        "minecraft:dead_horn_coral_block",
    ),
    block(737, "TUBE_CORAL_BLOCK", "minecraft:tube_coral_block"),
    block(738, "BRAIN_CORAL_BLOCK", "minecraft:brain_coral_block"),
    block(739, "BUBBLE_CORAL_BLOCK", "minecraft:bubble_coral_block"),
    block(740, "FIRE_CORAL_BLOCK", "minecraft:fire_coral_block"),
    block(741, "HORN_CORAL_BLOCK", "minecraft:horn_coral_block"),
    block(742, "DEAD_TUBE_CORAL", "minecraft:dead_tube_coral"),
    block(743, "DEAD_BRAIN_CORAL", "minecraft:dead_brain_coral"),
    block(744, "DEAD_BUBBLE_CORAL", "minecraft:dead_bubble_coral"),
    block(745, "DEAD_FIRE_CORAL", "minecraft:dead_fire_coral"),
    block(746, "DEAD_HORN_CORAL", "minecraft:dead_horn_coral"),
    block(747, "TUBE_CORAL", "minecraft:tube_coral"),
    block(748, "BRAIN_CORAL", "minecraft:brain_coral"),
    block(749, "BUBBLE_CORAL", "minecraft:bubble_coral"),
    block(750, "FIRE_CORAL", "minecraft:fire_coral"),
    block(751, "HORN_CORAL", "minecraft:horn_coral"),
    block(752, "DEAD_TUBE_CORAL_FAN", "minecraft:dead_tube_coral_fan"),
    block(
        753,
        "DEAD_BRAIN_CORAL_FAN",
        "minecraft:dead_brain_coral_fan",
    ),
    block(
        754,
        "DEAD_BUBBLE_CORAL_FAN",
        "minecraft:dead_bubble_coral_fan",
    ),
    block(755, "DEAD_FIRE_CORAL_FAN", "minecraft:dead_fire_coral_fan"),
    block(756, "DEAD_HORN_CORAL_FAN", "minecraft:dead_horn_coral_fan"),
    block(757, "TUBE_CORAL_FAN", "minecraft:tube_coral_fan"),
    block(758, "BRAIN_CORAL_FAN", "minecraft:brain_coral_fan"),
    block(759, "BUBBLE_CORAL_FAN", "minecraft:bubble_coral_fan"),
    block(760, "FIRE_CORAL_FAN", "minecraft:fire_coral_fan"),
    block(761, "HORN_CORAL_FAN", "minecraft:horn_coral_fan"),
    block(
        762,
        "DEAD_TUBE_CORAL_WALL_FAN",
        "minecraft:dead_tube_coral_wall_fan",
    ),
    block(
        763,
        "DEAD_BRAIN_CORAL_WALL_FAN",
        "minecraft:dead_brain_coral_wall_fan",
    ),
    block(
        764,
        "DEAD_BUBBLE_CORAL_WALL_FAN",
        "minecraft:dead_bubble_coral_wall_fan",
    ),
    block(
        765,
        "DEAD_FIRE_CORAL_WALL_FAN",
        "minecraft:dead_fire_coral_wall_fan",
    ),
    block(
        766,
        "DEAD_HORN_CORAL_WALL_FAN",
        "minecraft:dead_horn_coral_wall_fan",
    ),
    block(767, "TUBE_CORAL_WALL_FAN", "minecraft:tube_coral_wall_fan"),
    block(
        768,
        "BRAIN_CORAL_WALL_FAN",
        "minecraft:brain_coral_wall_fan",
    ),
    block(
        769,
        "BUBBLE_CORAL_WALL_FAN",
        "minecraft:bubble_coral_wall_fan",
    ),
    block(770, "FIRE_CORAL_WALL_FAN", "minecraft:fire_coral_wall_fan"),
    block(771, "HORN_CORAL_WALL_FAN", "minecraft:horn_coral_wall_fan"),
    block(772, "SEA_PICKLE", "minecraft:sea_pickle"),
    block(773, "BLUE_ICE", "minecraft:blue_ice"),
    block(774, "CONDUIT", "minecraft:conduit"),
    block(775, "BAMBOO_SAPLING", "minecraft:bamboo_sapling"),
    block(776, "BAMBOO", "minecraft:bamboo"),
    block(777, "POTTED_BAMBOO", "minecraft:potted_bamboo"),
    block(778, "VOID_AIR", "minecraft:void_air"),
    block(779, "CAVE_AIR", "minecraft:cave_air"),
    block(780, "BUBBLE_COLUMN", "minecraft:bubble_column"),
    block(
        781,
        "POLISHED_GRANITE_STAIRS",
        "minecraft:polished_granite_stairs",
    ),
    block(
        782,
        "SMOOTH_RED_SANDSTONE_STAIRS",
        "minecraft:smooth_red_sandstone_stairs",
    ),
    block(
        783,
        "MOSSY_STONE_BRICK_STAIRS",
        "minecraft:mossy_stone_brick_stairs",
    ),
    block(
        784,
        "POLISHED_DIORITE_STAIRS",
        "minecraft:polished_diorite_stairs",
    ),
    block(
        785,
        "MOSSY_COBBLESTONE_STAIRS",
        "minecraft:mossy_cobblestone_stairs",
    ),
    block(
        786,
        "END_STONE_BRICK_STAIRS",
        "minecraft:end_stone_brick_stairs",
    ),
    block(787, "STONE_STAIRS", "minecraft:stone_stairs"),
    block(
        788,
        "SMOOTH_SANDSTONE_STAIRS",
        "minecraft:smooth_sandstone_stairs",
    ),
    block(
        789,
        "SMOOTH_QUARTZ_STAIRS",
        "minecraft:smooth_quartz_stairs",
    ),
    block(790, "GRANITE_STAIRS", "minecraft:granite_stairs"),
    block(791, "ANDESITE_STAIRS", "minecraft:andesite_stairs"),
    block(
        792,
        "RED_NETHER_BRICK_STAIRS",
        "minecraft:red_nether_brick_stairs",
    ),
    block(
        793,
        "POLISHED_ANDESITE_STAIRS",
        "minecraft:polished_andesite_stairs",
    ),
    block(794, "DIORITE_STAIRS", "minecraft:diorite_stairs"),
    block(
        795,
        "POLISHED_GRANITE_SLAB",
        "minecraft:polished_granite_slab",
    ),
    block(
        796,
        "SMOOTH_RED_SANDSTONE_SLAB",
        "minecraft:smooth_red_sandstone_slab",
    ),
    block(
        797,
        "MOSSY_STONE_BRICK_SLAB",
        "minecraft:mossy_stone_brick_slab",
    ),
    block(
        798,
        "POLISHED_DIORITE_SLAB",
        "minecraft:polished_diorite_slab",
    ),
    block(
        799,
        "MOSSY_COBBLESTONE_SLAB",
        "minecraft:mossy_cobblestone_slab",
    ),
    block(
        800,
        "END_STONE_BRICK_SLAB",
        "minecraft:end_stone_brick_slab",
    ),
    block(
        801,
        "SMOOTH_SANDSTONE_SLAB",
        "minecraft:smooth_sandstone_slab",
    ),
    block(802, "SMOOTH_QUARTZ_SLAB", "minecraft:smooth_quartz_slab"),
    block(803, "GRANITE_SLAB", "minecraft:granite_slab"),
    block(804, "ANDESITE_SLAB", "minecraft:andesite_slab"),
    block(
        805,
        "RED_NETHER_BRICK_SLAB",
        "minecraft:red_nether_brick_slab",
    ),
    block(
        806,
        "POLISHED_ANDESITE_SLAB",
        "minecraft:polished_andesite_slab",
    ),
    block(807, "DIORITE_SLAB", "minecraft:diorite_slab"),
    block(808, "BRICK_WALL", "minecraft:brick_wall"),
    block(809, "PRISMARINE_WALL", "minecraft:prismarine_wall"),
    block(810, "RED_SANDSTONE_WALL", "minecraft:red_sandstone_wall"),
    block(
        811,
        "MOSSY_STONE_BRICK_WALL",
        "minecraft:mossy_stone_brick_wall",
    ),
    block(812, "GRANITE_WALL", "minecraft:granite_wall"),
    block(813, "STONE_BRICK_WALL", "minecraft:stone_brick_wall"),
    block(814, "MUD_BRICK_WALL", "minecraft:mud_brick_wall"),
    block(815, "NETHER_BRICK_WALL", "minecraft:nether_brick_wall"),
    block(816, "ANDESITE_WALL", "minecraft:andesite_wall"),
    block(
        817,
        "RED_NETHER_BRICK_WALL",
        "minecraft:red_nether_brick_wall",
    ),
    block(818, "SANDSTONE_WALL", "minecraft:sandstone_wall"),
    block(
        819,
        "END_STONE_BRICK_WALL",
        "minecraft:end_stone_brick_wall",
    ),
    block(820, "DIORITE_WALL", "minecraft:diorite_wall"),
    block(821, "SCAFFOLDING", "minecraft:scaffolding"),
    block(822, "LOOM", "minecraft:loom"),
    block(823, "BARREL", "minecraft:barrel"),
    block(824, "SMOKER", "minecraft:smoker"),
    block(825, "BLAST_FURNACE", "minecraft:blast_furnace"),
    block(826, "CARTOGRAPHY_TABLE", "minecraft:cartography_table"),
    block(827, "FLETCHING_TABLE", "minecraft:fletching_table"),
    block(828, "GRINDSTONE", "minecraft:grindstone"),
    block(829, "LECTERN", "minecraft:lectern"),
    block(830, "SMITHING_TABLE", "minecraft:smithing_table"),
    block(831, "STONECUTTER", "minecraft:stonecutter"),
    block(832, "BELL", "minecraft:bell"),
    block(833, "LANTERN", "minecraft:lantern"),
    block(834, "SOUL_LANTERN", "minecraft:soul_lantern"),
    block(835, "CAMPFIRE", "minecraft:campfire"),
    block(836, "SOUL_CAMPFIRE", "minecraft:soul_campfire"),
    block(837, "SWEET_BERRY_BUSH", "minecraft:sweet_berry_bush"),
    block(838, "WARPED_STEM", "minecraft:warped_stem"),
    block(
        839,
        "STRIPPED_WARPED_STEM",
        "minecraft:stripped_warped_stem",
    ),
    block(840, "WARPED_HYPHAE", "minecraft:warped_hyphae"),
    block(
        841,
        "STRIPPED_WARPED_HYPHAE",
        "minecraft:stripped_warped_hyphae",
    ),
    block(842, "WARPED_NYLIUM", "minecraft:warped_nylium"),
    block(843, "WARPED_FUNGUS", "minecraft:warped_fungus"),
    block(844, "WARPED_WART_BLOCK", "minecraft:warped_wart_block"),
    block(845, "WARPED_ROOTS", "minecraft:warped_roots"),
    block(846, "NETHER_SPROUTS", "minecraft:nether_sprouts"),
    block(847, "CRIMSON_STEM", "minecraft:crimson_stem"),
    block(
        848,
        "STRIPPED_CRIMSON_STEM",
        "minecraft:stripped_crimson_stem",
    ),
    block(849, "CRIMSON_HYPHAE", "minecraft:crimson_hyphae"),
    block(
        850,
        "STRIPPED_CRIMSON_HYPHAE",
        "minecraft:stripped_crimson_hyphae",
    ),
    block(851, "CRIMSON_NYLIUM", "minecraft:crimson_nylium"),
    block(852, "CRIMSON_FUNGUS", "minecraft:crimson_fungus"),
    block(853, "SHROOMLIGHT", "minecraft:shroomlight"),
    block(854, "WEEPING_VINES", "minecraft:weeping_vines"),
    block(855, "WEEPING_VINES_PLANT", "minecraft:weeping_vines_plant"),
    block(856, "TWISTING_VINES", "minecraft:twisting_vines"),
    block(
        857,
        "TWISTING_VINES_PLANT",
        "minecraft:twisting_vines_plant",
    ),
    block(858, "CRIMSON_ROOTS", "minecraft:crimson_roots"),
    block(859, "CRIMSON_PLANKS", "minecraft:crimson_planks"),
    block(860, "WARPED_PLANKS", "minecraft:warped_planks"),
    block(861, "CRIMSON_SLAB", "minecraft:crimson_slab"),
    block(862, "WARPED_SLAB", "minecraft:warped_slab"),
    block(
        863,
        "CRIMSON_PRESSURE_PLATE",
        "minecraft:crimson_pressure_plate",
    ),
    block(
        864,
        "WARPED_PRESSURE_PLATE",
        "minecraft:warped_pressure_plate",
    ),
    block(865, "CRIMSON_FENCE", "minecraft:crimson_fence"),
    block(866, "WARPED_FENCE", "minecraft:warped_fence"),
    block(867, "CRIMSON_TRAPDOOR", "minecraft:crimson_trapdoor"),
    block(868, "WARPED_TRAPDOOR", "minecraft:warped_trapdoor"),
    block(869, "CRIMSON_FENCE_GATE", "minecraft:crimson_fence_gate"),
    block(870, "WARPED_FENCE_GATE", "minecraft:warped_fence_gate"),
    block(871, "CRIMSON_STAIRS", "minecraft:crimson_stairs"),
    block(872, "WARPED_STAIRS", "minecraft:warped_stairs"),
    block(873, "CRIMSON_BUTTON", "minecraft:crimson_button"),
    block(874, "WARPED_BUTTON", "minecraft:warped_button"),
    block(875, "CRIMSON_DOOR", "minecraft:crimson_door"),
    block(876, "WARPED_DOOR", "minecraft:warped_door"),
    block(877, "CRIMSON_SIGN", "minecraft:crimson_sign"),
    block(878, "WARPED_SIGN", "minecraft:warped_sign"),
    block(879, "CRIMSON_WALL_SIGN", "minecraft:crimson_wall_sign"),
    block(880, "WARPED_WALL_SIGN", "minecraft:warped_wall_sign"),
    block(881, "STRUCTURE_BLOCK", "minecraft:structure_block"),
    block(882, "JIGSAW", "minecraft:jigsaw"),
    block(883, "TEST_BLOCK", "minecraft:test_block"),
    block(884, "TEST_INSTANCE_BLOCK", "minecraft:test_instance_block"),
    block(885, "COMPOSTER", "minecraft:composter"),
    block(886, "TARGET", "minecraft:target"),
    block(887, "BEE_NEST", "minecraft:bee_nest"),
    block(888, "BEEHIVE", "minecraft:beehive"),
    block(889, "HONEY_BLOCK", "minecraft:honey_block"),
    block(890, "HONEYCOMB_BLOCK", "minecraft:honeycomb_block"),
    block(891, "NETHERITE_BLOCK", "minecraft:netherite_block"),
    block(892, "ANCIENT_DEBRIS", "minecraft:ancient_debris"),
    block(893, "CRYING_OBSIDIAN", "minecraft:crying_obsidian"),
    block(894, "RESPAWN_ANCHOR", "minecraft:respawn_anchor"),
    block(
        895,
        "POTTED_CRIMSON_FUNGUS",
        "minecraft:potted_crimson_fungus",
    ),
    block(
        896,
        "POTTED_WARPED_FUNGUS",
        "minecraft:potted_warped_fungus",
    ),
    block(
        897,
        "POTTED_CRIMSON_ROOTS",
        "minecraft:potted_crimson_roots",
    ),
    block(898, "POTTED_WARPED_ROOTS", "minecraft:potted_warped_roots"),
    block(899, "LODESTONE", "minecraft:lodestone"),
    block(900, "BLACKSTONE", "minecraft:blackstone"),
    block(901, "BLACKSTONE_STAIRS", "minecraft:blackstone_stairs"),
    block(902, "BLACKSTONE_WALL", "minecraft:blackstone_wall"),
    block(903, "BLACKSTONE_SLAB", "minecraft:blackstone_slab"),
    block(904, "POLISHED_BLACKSTONE", "minecraft:polished_blackstone"),
    block(
        905,
        "POLISHED_BLACKSTONE_BRICKS",
        "minecraft:polished_blackstone_bricks",
    ),
    block(
        906,
        "CRACKED_POLISHED_BLACKSTONE_BRICKS",
        "minecraft:cracked_polished_blackstone_bricks",
    ),
    block(
        907,
        "CHISELED_POLISHED_BLACKSTONE",
        "minecraft:chiseled_polished_blackstone",
    ),
    block(
        908,
        "POLISHED_BLACKSTONE_BRICK_SLAB",
        "minecraft:polished_blackstone_brick_slab",
    ),
    block(
        909,
        "POLISHED_BLACKSTONE_BRICK_STAIRS",
        "minecraft:polished_blackstone_brick_stairs",
    ),
    block(
        910,
        "POLISHED_BLACKSTONE_BRICK_WALL",
        "minecraft:polished_blackstone_brick_wall",
    ),
    block(911, "GILDED_BLACKSTONE", "minecraft:gilded_blackstone"),
];
