use super::{block, BlockRegistryEntry};

pub(super) const ENTRIES: &[BlockRegistryEntry] = &[
    block(
        912,
        "POLISHED_BLACKSTONE_STAIRS",
        "minecraft:polished_blackstone_stairs",
    ),
    block(
        913,
        "POLISHED_BLACKSTONE_SLAB",
        "minecraft:polished_blackstone_slab",
    ),
    block(
        914,
        "POLISHED_BLACKSTONE_PRESSURE_PLATE",
        "minecraft:polished_blackstone_pressure_plate",
    ),
    block(
        915,
        "POLISHED_BLACKSTONE_BUTTON",
        "minecraft:polished_blackstone_button",
    ),
    block(
        916,
        "POLISHED_BLACKSTONE_WALL",
        "minecraft:polished_blackstone_wall",
    ),
    block(
        917,
        "CHISELED_NETHER_BRICKS",
        "minecraft:chiseled_nether_bricks",
    ),
    block(
        918,
        "CRACKED_NETHER_BRICKS",
        "minecraft:cracked_nether_bricks",
    ),
    block(919, "QUARTZ_BRICKS", "minecraft:quartz_bricks"),
    block(920, "CANDLE", "minecraft:candle"),
    block(921, "WHITE_CANDLE", "minecraft:white_candle"),
    block(922, "ORANGE_CANDLE", "minecraft:orange_candle"),
    block(923, "MAGENTA_CANDLE", "minecraft:magenta_candle"),
    block(924, "LIGHT_BLUE_CANDLE", "minecraft:light_blue_candle"),
    block(925, "YELLOW_CANDLE", "minecraft:yellow_candle"),
    block(926, "LIME_CANDLE", "minecraft:lime_candle"),
    block(927, "PINK_CANDLE", "minecraft:pink_candle"),
    block(928, "GRAY_CANDLE", "minecraft:gray_candle"),
    block(929, "LIGHT_GRAY_CANDLE", "minecraft:light_gray_candle"),
    block(930, "CYAN_CANDLE", "minecraft:cyan_candle"),
    block(931, "PURPLE_CANDLE", "minecraft:purple_candle"),
    block(932, "BLUE_CANDLE", "minecraft:blue_candle"),
    block(933, "BROWN_CANDLE", "minecraft:brown_candle"),
    block(934, "GREEN_CANDLE", "minecraft:green_candle"),
    block(935, "RED_CANDLE", "minecraft:red_candle"),
    block(936, "BLACK_CANDLE", "minecraft:black_candle"),
    block(937, "CANDLE_CAKE", "minecraft:candle_cake"),
    block(938, "WHITE_CANDLE_CAKE", "minecraft:white_candle_cake"),
    block(939, "ORANGE_CANDLE_CAKE", "minecraft:orange_candle_cake"),
    block(940, "MAGENTA_CANDLE_CAKE", "minecraft:magenta_candle_cake"),
    block(
        941,
        "LIGHT_BLUE_CANDLE_CAKE",
        "minecraft:light_blue_candle_cake",
    ),
    block(942, "YELLOW_CANDLE_CAKE", "minecraft:yellow_candle_cake"),
    block(943, "LIME_CANDLE_CAKE", "minecraft:lime_candle_cake"),
    block(944, "PINK_CANDLE_CAKE", "minecraft:pink_candle_cake"),
    block(945, "GRAY_CANDLE_CAKE", "minecraft:gray_candle_cake"),
    block(
        946,
        "LIGHT_GRAY_CANDLE_CAKE",
        "minecraft:light_gray_candle_cake",
    ),
    block(947, "CYAN_CANDLE_CAKE", "minecraft:cyan_candle_cake"),
    block(948, "PURPLE_CANDLE_CAKE", "minecraft:purple_candle_cake"),
    block(949, "BLUE_CANDLE_CAKE", "minecraft:blue_candle_cake"),
    block(950, "BROWN_CANDLE_CAKE", "minecraft:brown_candle_cake"),
    block(951, "GREEN_CANDLE_CAKE", "minecraft:green_candle_cake"),
    block(952, "RED_CANDLE_CAKE", "minecraft:red_candle_cake"),
    block(953, "BLACK_CANDLE_CAKE", "minecraft:black_candle_cake"),
    block(954, "AMETHYST_BLOCK", "minecraft:amethyst_block"),
    block(955, "BUDDING_AMETHYST", "minecraft:budding_amethyst"),
    block(956, "AMETHYST_CLUSTER", "minecraft:amethyst_cluster"),
    block(957, "LARGE_AMETHYST_BUD", "minecraft:large_amethyst_bud"),
    block(958, "MEDIUM_AMETHYST_BUD", "minecraft:medium_amethyst_bud"),
    block(959, "SMALL_AMETHYST_BUD", "minecraft:small_amethyst_bud"),
    block(960, "TUFF", "minecraft:tuff"),
    block(961, "TUFF_SLAB", "minecraft:tuff_slab"),
    block(962, "TUFF_STAIRS", "minecraft:tuff_stairs"),
    block(963, "TUFF_WALL", "minecraft:tuff_wall"),
    block(964, "POLISHED_TUFF", "minecraft:polished_tuff"),
    block(965, "POLISHED_TUFF_SLAB", "minecraft:polished_tuff_slab"),
    block(
        966,
        "POLISHED_TUFF_STAIRS",
        "minecraft:polished_tuff_stairs",
    ),
    block(967, "POLISHED_TUFF_WALL", "minecraft:polished_tuff_wall"),
    block(968, "CHISELED_TUFF", "minecraft:chiseled_tuff"),
    block(969, "TUFF_BRICKS", "minecraft:tuff_bricks"),
    block(970, "TUFF_BRICK_SLAB", "minecraft:tuff_brick_slab"),
    block(971, "TUFF_BRICK_STAIRS", "minecraft:tuff_brick_stairs"),
    block(972, "TUFF_BRICK_WALL", "minecraft:tuff_brick_wall"),
    block(
        973,
        "CHISELED_TUFF_BRICKS",
        "minecraft:chiseled_tuff_bricks",
    ),
    block(974, "CALCITE", "minecraft:calcite"),
    block(975, "TINTED_GLASS", "minecraft:tinted_glass"),
    block(976, "POWDER_SNOW", "minecraft:powder_snow"),
    block(977, "SCULK_SENSOR", "minecraft:sculk_sensor"),
    block(
        978,
        "CALIBRATED_SCULK_SENSOR",
        "minecraft:calibrated_sculk_sensor",
    ),
    block(979, "SCULK", "minecraft:sculk"),
    block(980, "SCULK_VEIN", "minecraft:sculk_vein"),
    block(981, "SCULK_CATALYST", "minecraft:sculk_catalyst"),
    block(982, "SCULK_SHRIEKER", "minecraft:sculk_shrieker"),
    block(983, "COPPER_BLOCK", "minecraft:copper_block"),
    block(984, "EXPOSED_COPPER", "minecraft:exposed_copper"),
    block(985, "WEATHERED_COPPER", "minecraft:weathered_copper"),
    block(986, "OXIDIZED_COPPER", "minecraft:oxidized_copper"),
    block(987, "COPPER_ORE", "minecraft:copper_ore"),
    block(
        988,
        "DEEPSLATE_COPPER_ORE",
        "minecraft:deepslate_copper_ore",
    ),
    block(989, "OXIDIZED_CUT_COPPER", "minecraft:oxidized_cut_copper"),
    block(
        990,
        "WEATHERED_CUT_COPPER",
        "minecraft:weathered_cut_copper",
    ),
    block(991, "EXPOSED_CUT_COPPER", "minecraft:exposed_cut_copper"),
    block(992, "CUT_COPPER", "minecraft:cut_copper"),
    block(
        993,
        "OXIDIZED_CHISELED_COPPER",
        "minecraft:oxidized_chiseled_copper",
    ),
    block(
        994,
        "WEATHERED_CHISELED_COPPER",
        "minecraft:weathered_chiseled_copper",
    ),
    block(
        995,
        "EXPOSED_CHISELED_COPPER",
        "minecraft:exposed_chiseled_copper",
    ),
    block(996, "CHISELED_COPPER", "minecraft:chiseled_copper"),
    block(
        997,
        "WAXED_OXIDIZED_CHISELED_COPPER",
        "minecraft:waxed_oxidized_chiseled_copper",
    ),
    block(
        998,
        "WAXED_WEATHERED_CHISELED_COPPER",
        "minecraft:waxed_weathered_chiseled_copper",
    ),
    block(
        999,
        "WAXED_EXPOSED_CHISELED_COPPER",
        "minecraft:waxed_exposed_chiseled_copper",
    ),
    block(
        1000,
        "WAXED_CHISELED_COPPER",
        "minecraft:waxed_chiseled_copper",
    ),
    block(
        1001,
        "OXIDIZED_CUT_COPPER_STAIRS",
        "minecraft:oxidized_cut_copper_stairs",
    ),
    block(
        1002,
        "WEATHERED_CUT_COPPER_STAIRS",
        "minecraft:weathered_cut_copper_stairs",
    ),
    block(
        1003,
        "EXPOSED_CUT_COPPER_STAIRS",
        "minecraft:exposed_cut_copper_stairs",
    ),
    block(1004, "CUT_COPPER_STAIRS", "minecraft:cut_copper_stairs"),
    block(
        1005,
        "OXIDIZED_CUT_COPPER_SLAB",
        "minecraft:oxidized_cut_copper_slab",
    ),
    block(
        1006,
        "WEATHERED_CUT_COPPER_SLAB",
        "minecraft:weathered_cut_copper_slab",
    ),
    block(
        1007,
        "EXPOSED_CUT_COPPER_SLAB",
        "minecraft:exposed_cut_copper_slab",
    ),
    block(1008, "CUT_COPPER_SLAB", "minecraft:cut_copper_slab"),
    block(1009, "WAXED_COPPER_BLOCK", "minecraft:waxed_copper_block"),
    block(
        1010,
        "WAXED_WEATHERED_COPPER",
        "minecraft:waxed_weathered_copper",
    ),
    block(
        1011,
        "WAXED_EXPOSED_COPPER",
        "minecraft:waxed_exposed_copper",
    ),
    block(
        1012,
        "WAXED_OXIDIZED_COPPER",
        "minecraft:waxed_oxidized_copper",
    ),
    block(
        1013,
        "WAXED_OXIDIZED_CUT_COPPER",
        "minecraft:waxed_oxidized_cut_copper",
    ),
    block(
        1014,
        "WAXED_WEATHERED_CUT_COPPER",
        "minecraft:waxed_weathered_cut_copper",
    ),
    block(
        1015,
        "WAXED_EXPOSED_CUT_COPPER",
        "minecraft:waxed_exposed_cut_copper",
    ),
    block(1016, "WAXED_CUT_COPPER", "minecraft:waxed_cut_copper"),
    block(
        1017,
        "WAXED_OXIDIZED_CUT_COPPER_STAIRS",
        "minecraft:waxed_oxidized_cut_copper_stairs",
    ),
    block(
        1018,
        "WAXED_WEATHERED_CUT_COPPER_STAIRS",
        "minecraft:waxed_weathered_cut_copper_stairs",
    ),
    block(
        1019,
        "WAXED_EXPOSED_CUT_COPPER_STAIRS",
        "minecraft:waxed_exposed_cut_copper_stairs",
    ),
    block(
        1020,
        "WAXED_CUT_COPPER_STAIRS",
        "minecraft:waxed_cut_copper_stairs",
    ),
    block(
        1021,
        "WAXED_OXIDIZED_CUT_COPPER_SLAB",
        "minecraft:waxed_oxidized_cut_copper_slab",
    ),
    block(
        1022,
        "WAXED_WEATHERED_CUT_COPPER_SLAB",
        "minecraft:waxed_weathered_cut_copper_slab",
    ),
    block(
        1023,
        "WAXED_EXPOSED_CUT_COPPER_SLAB",
        "minecraft:waxed_exposed_cut_copper_slab",
    ),
    block(
        1024,
        "WAXED_CUT_COPPER_SLAB",
        "minecraft:waxed_cut_copper_slab",
    ),
    block(1025, "COPPER_DOOR", "minecraft:copper_door"),
    block(1026, "EXPOSED_COPPER_DOOR", "minecraft:exposed_copper_door"),
    block(
        1027,
        "OXIDIZED_COPPER_DOOR",
        "minecraft:oxidized_copper_door",
    ),
    block(
        1028,
        "WEATHERED_COPPER_DOOR",
        "minecraft:weathered_copper_door",
    ),
    block(1029, "WAXED_COPPER_DOOR", "minecraft:waxed_copper_door"),
    block(
        1030,
        "WAXED_EXPOSED_COPPER_DOOR",
        "minecraft:waxed_exposed_copper_door",
    ),
    block(
        1031,
        "WAXED_OXIDIZED_COPPER_DOOR",
        "minecraft:waxed_oxidized_copper_door",
    ),
    block(
        1032,
        "WAXED_WEATHERED_COPPER_DOOR",
        "minecraft:waxed_weathered_copper_door",
    ),
    block(1033, "COPPER_TRAPDOOR", "minecraft:copper_trapdoor"),
    block(
        1034,
        "EXPOSED_COPPER_TRAPDOOR",
        "minecraft:exposed_copper_trapdoor",
    ),
    block(
        1035,
        "OXIDIZED_COPPER_TRAPDOOR",
        "minecraft:oxidized_copper_trapdoor",
    ),
    block(
        1036,
        "WEATHERED_COPPER_TRAPDOOR",
        "minecraft:weathered_copper_trapdoor",
    ),
    block(
        1037,
        "WAXED_COPPER_TRAPDOOR",
        "minecraft:waxed_copper_trapdoor",
    ),
    block(
        1038,
        "WAXED_EXPOSED_COPPER_TRAPDOOR",
        "minecraft:waxed_exposed_copper_trapdoor",
    ),
    block(
        1039,
        "WAXED_OXIDIZED_COPPER_TRAPDOOR",
        "minecraft:waxed_oxidized_copper_trapdoor",
    ),
    block(
        1040,
        "WAXED_WEATHERED_COPPER_TRAPDOOR",
        "minecraft:waxed_weathered_copper_trapdoor",
    ),
    block(1041, "COPPER_GRATE", "minecraft:copper_grate"),
    block(
        1042,
        "EXPOSED_COPPER_GRATE",
        "minecraft:exposed_copper_grate",
    ),
    block(
        1043,
        "WEATHERED_COPPER_GRATE",
        "minecraft:weathered_copper_grate",
    ),
    block(
        1044,
        "OXIDIZED_COPPER_GRATE",
        "minecraft:oxidized_copper_grate",
    ),
    block(1045, "WAXED_COPPER_GRATE", "minecraft:waxed_copper_grate"),
    block(
        1046,
        "WAXED_EXPOSED_COPPER_GRATE",
        "minecraft:waxed_exposed_copper_grate",
    ),
    block(
        1047,
        "WAXED_WEATHERED_COPPER_GRATE",
        "minecraft:waxed_weathered_copper_grate",
    ),
    block(
        1048,
        "WAXED_OXIDIZED_COPPER_GRATE",
        "minecraft:waxed_oxidized_copper_grate",
    ),
    block(1049, "COPPER_BULB", "minecraft:copper_bulb"),
    block(1050, "EXPOSED_COPPER_BULB", "minecraft:exposed_copper_bulb"),
    block(
        1051,
        "WEATHERED_COPPER_BULB",
        "minecraft:weathered_copper_bulb",
    ),
    block(
        1052,
        "OXIDIZED_COPPER_BULB",
        "minecraft:oxidized_copper_bulb",
    ),
    block(1053, "WAXED_COPPER_BULB", "minecraft:waxed_copper_bulb"),
    block(
        1054,
        "WAXED_EXPOSED_COPPER_BULB",
        "minecraft:waxed_exposed_copper_bulb",
    ),
    block(
        1055,
        "WAXED_WEATHERED_COPPER_BULB",
        "minecraft:waxed_weathered_copper_bulb",
    ),
    block(
        1056,
        "WAXED_OXIDIZED_COPPER_BULB",
        "minecraft:waxed_oxidized_copper_bulb",
    ),
    block(1057, "COPPER_CHEST", "minecraft:copper_chest"),
    block(
        1058,
        "EXPOSED_COPPER_CHEST",
        "minecraft:exposed_copper_chest",
    ),
    block(
        1059,
        "WEATHERED_COPPER_CHEST",
        "minecraft:weathered_copper_chest",
    ),
    block(
        1060,
        "OXIDIZED_COPPER_CHEST",
        "minecraft:oxidized_copper_chest",
    ),
    block(1061, "WAXED_COPPER_CHEST", "minecraft:waxed_copper_chest"),
    block(
        1062,
        "WAXED_EXPOSED_COPPER_CHEST",
        "minecraft:waxed_exposed_copper_chest",
    ),
    block(
        1063,
        "WAXED_WEATHERED_COPPER_CHEST",
        "minecraft:waxed_weathered_copper_chest",
    ),
    block(
        1064,
        "WAXED_OXIDIZED_COPPER_CHEST",
        "minecraft:waxed_oxidized_copper_chest",
    ),
    block(1065, "COPPER_GOLEM_STATUE", "minecraft:copper_golem_statue"),
    block(
        1066,
        "EXPOSED_COPPER_GOLEM_STATUE",
        "minecraft:exposed_copper_golem_statue",
    ),
    block(
        1067,
        "WEATHERED_COPPER_GOLEM_STATUE",
        "minecraft:weathered_copper_golem_statue",
    ),
    block(
        1068,
        "OXIDIZED_COPPER_GOLEM_STATUE",
        "minecraft:oxidized_copper_golem_statue",
    ),
    block(
        1069,
        "WAXED_COPPER_GOLEM_STATUE",
        "minecraft:waxed_copper_golem_statue",
    ),
    block(
        1070,
        "WAXED_EXPOSED_COPPER_GOLEM_STATUE",
        "minecraft:waxed_exposed_copper_golem_statue",
    ),
    block(
        1071,
        "WAXED_WEATHERED_COPPER_GOLEM_STATUE",
        "minecraft:waxed_weathered_copper_golem_statue",
    ),
    block(
        1072,
        "WAXED_OXIDIZED_COPPER_GOLEM_STATUE",
        "minecraft:waxed_oxidized_copper_golem_statue",
    ),
    block(1073, "LIGHTNING_ROD", "minecraft:lightning_rod"),
    block(
        1074,
        "EXPOSED_LIGHTNING_ROD",
        "minecraft:exposed_lightning_rod",
    ),
    block(
        1075,
        "WEATHERED_LIGHTNING_ROD",
        "minecraft:weathered_lightning_rod",
    ),
    block(
        1076,
        "OXIDIZED_LIGHTNING_ROD",
        "minecraft:oxidized_lightning_rod",
    ),
    block(1077, "WAXED_LIGHTNING_ROD", "minecraft:waxed_lightning_rod"),
    block(
        1078,
        "WAXED_EXPOSED_LIGHTNING_ROD",
        "minecraft:waxed_exposed_lightning_rod",
    ),
    block(
        1079,
        "WAXED_WEATHERED_LIGHTNING_ROD",
        "minecraft:waxed_weathered_lightning_rod",
    ),
    block(
        1080,
        "WAXED_OXIDIZED_LIGHTNING_ROD",
        "minecraft:waxed_oxidized_lightning_rod",
    ),
    block(1081, "POINTED_DRIPSTONE", "minecraft:pointed_dripstone"),
    block(1082, "DRIPSTONE_BLOCK", "minecraft:dripstone_block"),
    block(1083, "CAVE_VINES", "minecraft:cave_vines"),
    block(1084, "CAVE_VINES_PLANT", "minecraft:cave_vines_plant"),
    block(1085, "SPORE_BLOSSOM", "minecraft:spore_blossom"),
    block(1086, "AZALEA", "minecraft:azalea"),
    block(1087, "FLOWERING_AZALEA", "minecraft:flowering_azalea"),
    block(1088, "MOSS_CARPET", "minecraft:moss_carpet"),
    block(1089, "PINK_PETALS", "minecraft:pink_petals"),
    block(1090, "WILDFLOWERS", "minecraft:wildflowers"),
    block(1091, "LEAF_LITTER", "minecraft:leaf_litter"),
    block(1092, "MOSS_BLOCK", "minecraft:moss_block"),
    block(1093, "BIG_DRIPLEAF", "minecraft:big_dripleaf"),
    block(1094, "BIG_DRIPLEAF_STEM", "minecraft:big_dripleaf_stem"),
    block(1095, "SMALL_DRIPLEAF", "minecraft:small_dripleaf"),
    block(1096, "HANGING_ROOTS", "minecraft:hanging_roots"),
    block(1097, "ROOTED_DIRT", "minecraft:rooted_dirt"),
    block(1098, "MUD", "minecraft:mud"),
    block(1099, "DEEPSLATE", "minecraft:deepslate"),
    block(1100, "COBBLED_DEEPSLATE", "minecraft:cobbled_deepslate"),
    block(
        1101,
        "COBBLED_DEEPSLATE_STAIRS",
        "minecraft:cobbled_deepslate_stairs",
    ),
    block(
        1102,
        "COBBLED_DEEPSLATE_SLAB",
        "minecraft:cobbled_deepslate_slab",
    ),
    block(
        1103,
        "COBBLED_DEEPSLATE_WALL",
        "minecraft:cobbled_deepslate_wall",
    ),
    block(1104, "POLISHED_DEEPSLATE", "minecraft:polished_deepslate"),
    block(
        1105,
        "POLISHED_DEEPSLATE_STAIRS",
        "minecraft:polished_deepslate_stairs",
    ),
    block(
        1106,
        "POLISHED_DEEPSLATE_SLAB",
        "minecraft:polished_deepslate_slab",
    ),
    block(
        1107,
        "POLISHED_DEEPSLATE_WALL",
        "minecraft:polished_deepslate_wall",
    ),
    block(1108, "DEEPSLATE_TILES", "minecraft:deepslate_tiles"),
    block(
        1109,
        "DEEPSLATE_TILE_STAIRS",
        "minecraft:deepslate_tile_stairs",
    ),
    block(1110, "DEEPSLATE_TILE_SLAB", "minecraft:deepslate_tile_slab"),
    block(1111, "DEEPSLATE_TILE_WALL", "minecraft:deepslate_tile_wall"),
    block(1112, "DEEPSLATE_BRICKS", "minecraft:deepslate_bricks"),
    block(
        1113,
        "DEEPSLATE_BRICK_STAIRS",
        "minecraft:deepslate_brick_stairs",
    ),
    block(
        1114,
        "DEEPSLATE_BRICK_SLAB",
        "minecraft:deepslate_brick_slab",
    ),
    block(
        1115,
        "DEEPSLATE_BRICK_WALL",
        "minecraft:deepslate_brick_wall",
    ),
    block(1116, "CHISELED_DEEPSLATE", "minecraft:chiseled_deepslate"),
    block(
        1117,
        "CRACKED_DEEPSLATE_BRICKS",
        "minecraft:cracked_deepslate_bricks",
    ),
    block(
        1118,
        "CRACKED_DEEPSLATE_TILES",
        "minecraft:cracked_deepslate_tiles",
    ),
    block(1119, "INFESTED_DEEPSLATE", "minecraft:infested_deepslate"),
    block(1120, "SMOOTH_BASALT", "minecraft:smooth_basalt"),
    block(1121, "RAW_IRON_BLOCK", "minecraft:raw_iron_block"),
    block(1122, "RAW_COPPER_BLOCK", "minecraft:raw_copper_block"),
    block(1123, "RAW_GOLD_BLOCK", "minecraft:raw_gold_block"),
    block(1124, "POTTED_AZALEA", "minecraft:potted_azalea_bush"),
    block(
        1125,
        "POTTED_FLOWERING_AZALEA",
        "minecraft:potted_flowering_azalea_bush",
    ),
    block(1126, "OCHRE_FROGLIGHT", "minecraft:ochre_froglight"),
    block(1127, "VERDANT_FROGLIGHT", "minecraft:verdant_froglight"),
    block(
        1128,
        "PEARLESCENT_FROGLIGHT",
        "minecraft:pearlescent_froglight",
    ),
    block(1129, "FROGSPAWN", "minecraft:frogspawn"),
    block(
        1130,
        "REINFORCED_DEEPSLATE",
        "minecraft:reinforced_deepslate",
    ),
    block(1131, "DECORATED_POT", "minecraft:decorated_pot"),
    block(1132, "CRAFTER", "minecraft:crafter"),
    block(1133, "TRIAL_SPAWNER", "minecraft:trial_spawner"),
    block(1134, "VAULT", "minecraft:vault"),
    block(1135, "HEAVY_CORE", "minecraft:heavy_core"),
    block(1136, "PALE_MOSS_BLOCK", "minecraft:pale_moss_block"),
    block(1137, "PALE_MOSS_CARPET", "minecraft:pale_moss_carpet"),
    block(1138, "PALE_HANGING_MOSS", "minecraft:pale_hanging_moss"),
    block(1139, "OPEN_EYEBLOSSOM", "minecraft:open_eyeblossom"),
    block(1140, "CLOSED_EYEBLOSSOM", "minecraft:closed_eyeblossom"),
    block(
        1141,
        "POTTED_OPEN_EYEBLOSSOM",
        "minecraft:potted_open_eyeblossom",
    ),
    block(
        1142,
        "POTTED_CLOSED_EYEBLOSSOM",
        "minecraft:potted_closed_eyeblossom",
    ),
    block(1143, "FIREFLY_BUSH", "minecraft:firefly_bush"),
];
